# Generated by Django 5.1.15 on 2026-04-18 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_marketplacepartner_marketplaceselleraccount'),
        ('products', '0003_product_additional_images_product_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this product was updated via marketplace sync', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_partner',
            field=models.ForeignKey(blank=True, help_text='Which marketplace synced this product (if source=marketplace)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_products', to='partners.marketplacepartner'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('snap', 'Snap to Sell'), ('csv', 'CSV Import'), ('api', 'API'), ('marketplace', 'Marketplace Sync')], default='manual', max_length=15),
        ),
    ]
