# Generated by Django 5.1.15 on 2026-04-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_last_synced_at_product_marketplace_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Marketplace-specific product data that doesn\'t map to Kova fields. E.g. {"condition": "used", "old_price": 5000, "variants": [{"size": "XL"}], "specifications": [{"key": "Material", "value": "Cotton"}], "campus_codes": ["USIU", "KU"], "vendor_net_price": 4500, "commission_pct": 10}'),
        ),
    ]
