# Generated by Django 5.1.15 on 2026-04-18 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_voicebrief'),
        ('products', '0005_product_marketplace_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Photo of delivery receipt, invoice, or packing list', upload_to='restock_scans/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'AI Analyzing Receipt'), ('matching', 'Matching Products'), ('updating', 'Updating Stock'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=15)),
                ('extracted_items', models.JSONField(blank=True, default=list, help_text='Items extracted from receipt by AI vision:\n[{"name": "Samsung A54", "quantity": 10, "unit_price": 42000,\n  "matched_product_id": "uuid-here", "match_confidence": 0.92},\n {"name": "iPhone 15 Case", "quantity": 50, "unit_price": 500,\n  "matched_product_id": null, "match_confidence": 0}]')),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier/vendor name extracted from receipt', max_length=200)),
                ('receipt_date', models.DateField(blank=True, help_text='Date on the receipt (if extracted)', null=True)),
                ('receipt_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount on the receipt (if extracted)', max_digits=12, null=True)),
                ('receipt_currency', models.CharField(default='KES', max_length=5)),
                ('products_matched', models.PositiveIntegerField(default=0, help_text='Number of extracted items matched to existing products')),
                ('products_updated', models.PositiveIntegerField(default=0, help_text='Number of products whose stock was actually updated')),
                ('items_not_matched', models.JSONField(blank=True, default=list, help_text="Items that couldn't be matched to existing products")),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_seed', models.ForeignKey(blank=True, help_text="ContentSeed for 'back in stock' posts (auto-generated)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_scans', to='content.contentseed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='products_re_user_id_6b1bb1_idx'), models.Index(fields=['user', '-created_at'], name='products_re_user_id_6649e7_idx')],
            },
        ),
    ]
