# Generated by Django 5.1.15 on 2026-05-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_commerce_payment_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchsnapsession',
            new_name='products_ba_user_id_fb62ca_idx',
            old_name='products_ba_user_id_6a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='batchsnapsession',
            new_name='products_ba_user_id_6a22a8_idx',
            old_name='products_ba_user_id_9c4e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='products_co_user_id_9ffcb4_idx',
            old_name='products_co_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='products_co_product_062b8a_idx',
            old_name='products_co_product_idx',
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='products_co_status_c01cbb_idx',
            old_name='products_co_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='products_co_transac_be8abb_idx',
            old_name='products_co_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_user_id_30ea19_idx',
            old_name='products_pr_user_co_idx',
        ),
    ]
