# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_products_ba_user_id_6a8f2d_idx_products_ba_user_id_fb62ca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercepayment',
            name='transaction_ref',
            field=models.CharField(db_index=True, help_text='Idempotency key: user_id:product_id:phone:timestamp_bucket', max_length=255, unique=True),
        ),
    ]
