# Generated by Django 5.1.15 on 2026-04-05 13:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('audience_description', models.TextField(help_text='Describe your audience, channels, and how you plan to promote Kova.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked Kova account (optional at application time)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, help_text='Unique code like KOVA-JAMES-A3X7', max_length=30, unique=True)),
                ('tier', models.CharField(choices=[('starter', 'Starter (15%)'), ('connector', 'Connector (20%)'), ('catalyst', 'Catalyst (25%)'), ('powerhouse', 'Powerhouse (30%)')], default='starter', max_length=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Current commission rate (0.15 = 15%)', max_digits=4)),
                ('profit_share_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quarterly profit share rate (0.00 = not eligible)', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('total_earned_kes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pending_payout_kes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='partners.partnerapplication')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(max_length=30)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='Set when client completes 2 consecutive paid months', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if client canceled or was flagged')),
                ('commission_expires_at', models.DateTimeField(blank=True, help_text='24 months from first payment', null=True)),
                ('consecutive_paid_months', models.PositiveIntegerField(default=0)),
                ('current_plan', models.CharField(blank=True, max_length=20)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='partners.partner')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_up_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('client_revenue_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.partner')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.referral')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_required', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('bonus_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.CharField(blank=True, max_length=200)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='partners.partner')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('partner', 'clients_required')},
            },
        ),
    ]
