# Generated by Django 5.1.15 on 2026-04-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_referral_referred_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Why this referral was flagged (IP clustering, disposable email, etc.)'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='True if referral triggered anti-fraud checks'),
        ),
        migrations.AddField(
            model_name='referral',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address at signup — used for sybil detection', null=True),
        ),
    ]
