# Generated by Django 5.1.15 on 2026-04-18 00:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_referral_flag_reason_referral_is_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Marketplace name (e.g. 'Jumia Kenya', 'Jiji Nigeria')", max_length=200)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'jumia-ke', 'jiji-ng')", max_length=80, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('api_key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the API key — raw key shown only on creation', max_length=64, unique=True)),
                ('api_key_prefix', models.CharField(help_text="First 8 chars of the key for identification (e.g. 'kmp_a3x7')", max_length=8)),
                ('api_key_created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key_last_used', models.DateTimeField(blank=True, null=True)),
                ('seller_identity_field', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('external_id', 'Marketplace Seller ID')], default='email', help_text='How this marketplace identifies sellers — determines provisioning lookup', max_length=15)),
                ('auto_activate_sellers', models.BooleanField(default=True, help_text='If True, sellers are active immediately. If False, seller must confirm/opt-in.')),
                ('seller_default_plan', models.CharField(default='growth', help_text='Plan tier assigned to provisioned sellers (starter/growth/pro/agency)', max_length=20)),
                ('max_sellers', models.PositiveIntegerField(default=1000, help_text='Contract limit on total provisioned sellers')),
                ('seller_welcome_email', models.BooleanField(default=True, help_text='Send welcome/activation email to provisioned sellers')),
                ('sync_direction', models.CharField(choices=[('push', 'Push (Marketplace → Kova)'), ('pull', 'Pull (Kova fetches from Marketplace)'), ('both', 'Bidirectional Sync')], default='push', max_length=10)),
                ('auto_snap_on_sync', models.BooleanField(default=True, help_text='Auto-trigger Snap to Sell vision AI when products are synced')),
                ('enforce_marketplace_cta', models.BooleanField(default=True, help_text='Force all generated content to link back to marketplace product pages')),
                ('product_field_mapping', models.JSONField(blank=True, default=dict, help_text='Maps marketplace product fields to Kova fields. E.g. {"title": "name", "sku": "external_id", "link": "product_url", "amount": "price", "photo": "image_url"}')),
                ('default_product_currency', models.CharField(default='KES', help_text="Currency for products if marketplace doesn't send currency per product", max_length=5)),
                ('billing_model', models.CharField(choices=[('per_seller', 'Per Active Seller / Month'), ('flat_fee', 'Flat Monthly Fee'), ('revenue_share', 'Revenue Share'), ('free_pilot', 'Free Pilot (time-limited)')], default='per_seller', max_length=15)),
                ('rate_per_seller_kes', models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Monthly rate per active seller (for per_seller billing)', max_digits=10)),
                ('flat_fee_kes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly flat fee (for flat_fee billing)', max_digits=12)),
                ('revenue_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of seller subscription revenue shared (for revenue_share billing)', max_digits=5)),
                ('pilot_expires_at', models.DateTimeField(blank=True, help_text='When the free pilot period ends (for free_pilot billing)', null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Marketplace-specific config. Examples:\n{"allowed_platforms": ["instagram", "facebook", "tiktok"]}\n{"content_approval_required": true}\n{"max_products_per_seller": 200}\n{"branding": {"accent_color": "#F68B1E", "powered_by_text": "Powered by Kova"}}\n{"webhook_events": ["seller.activated", "content.generated", "product.synced"]}\n{"restricted_content_types": ["meme"]}')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive event notifications (seller activated, content generated, etc.)')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for signing webhook payloads (HMAC-SHA256)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this partnership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(help_text='Links to referral partner for commission tracking', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='partners.partner')),
            ],
            options={
                'verbose_name': 'marketplace partner',
                'verbose_name_plural': 'marketplace partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSellerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_seller_id', models.CharField(help_text="Marketplace's ID for this seller (e.g. Jumia seller ID, Jiji vendor code)", max_length=255)),
                ('status', models.CharField(choices=[('invited', 'Invited (pending activation)'), ('active', 'Active'), ('suspended', 'Suspended by marketplace'), ('churned', 'Churned / Deactivated')], default='invited', max_length=12)),
                ('seller_metadata', models.JSONField(blank=True, default=dict, help_text='Marketplace-specific seller info. Examples:\n{"shop_name": "Jane Electronics", "shop_url": "https://jumia.co.ke/jane-electronics"}\n{"seller_tier": "gold", "store_rating": 4.7}\n{"location": "Nairobi", "category": "Electronics"}')),
                ('products_synced', models.PositiveIntegerField(default=0)),
                ('last_product_sync', models.DateTimeField(blank=True, null=True)),
                ('content_generated', models.PositiveIntegerField(default=0, help_text='Total content pieces generated for this seller via marketplace')),
                ('provisioned_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_accounts', to='partners.marketplacepartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_seller_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'marketplace seller account',
                'verbose_name_plural': 'marketplace seller accounts',
                'ordering': ['-provisioned_at'],
                'indexes': [models.Index(fields=['marketplace', 'status'], name='partners_ma_marketp_aca7e6_idx'), models.Index(fields=['external_seller_id'], name='partners_ma_externa_d5881e_idx')],
                'unique_together': {('marketplace', 'external_seller_id'), ('marketplace', 'user')},
            },
        ),
    ]
