# Generated by Django 5.1.15 on 2026-03-31 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tier', models.CharField(max_length=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('subscription_period_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='billingevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='stripe_event_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['provider', '-created_at'], name='billing_bil_provide_e0ca1c_idx'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['user', '-created_at'], name='billing_mpe_user_id_d5afab_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['status', '-created_at'], name='billing_mpe_status_4ee7f4_idx'),
        ),
    ]
