# Generated by Django 4.2.23 on 2026-06-24 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0008_rename_billing_csq_user_created_idx_billing_con_user_id_ccb309_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='addon_pack_id',
            field=models.CharField(blank=True, help_text='boost, scale, or burst when payment_kind=campaign_addon', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='payment_kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('campaign_addon', 'Campaign add-on')], default='subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentseedquotalog',
            name='action',
            field=models.CharField(choices=[('reset_usage', 'Reset usage counter'), ('set_limit_override', 'Set monthly limit override'), ('clear_limit_override', 'Clear limit override'), ('set_bonus', 'Set bonus seeds'), ('addon_purchase', 'Campaign add-on purchase'), ('clear_all', 'Clear all overrides')], max_length=32),
        ),
        migrations.CreateModel(
            name='CampaignAddonPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(max_length=20)),
                ('campaigns_granted', models.PositiveIntegerField()),
                ('bonus_before', models.PositiveIntegerField(default=0)),
                ('bonus_after', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpesa_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='addon_purchase', to='billing.mpesapayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_addon_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_cam_user_id_947092_idx'), models.Index(fields=['pack_id', '-created_at'], name='billing_cam_pack_id_6ec41f_idx')],
            },
        ),
    ]
