# Generated by Django 5.1.15 on 2026-03-27 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform', 'username'],
                'unique_together': {('user', 'platform', 'platform_user_id')},
            },
        ),
    ]
