# Generated by Django 5.1.15 on 2026-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last OAuth or API error message'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time we successfully called the API', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_scope',
            field=models.TextField(blank=True, help_text='OAuth scopes granted by the user'),
        ),
    ]
