# Generated by Django 5.1.15 on 2026-04-06 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_socialaccount_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'is_active', '-last_synced_at'], name='platforms_s_user_id_479427_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['is_active', 'token_expires_at'], name='platforms_s_is_acti_a164ea_idx'),
        ),
    ]
