# Generated by Django 5.1.15 on 2026-03-27 01:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('daily_brief_time', models.TimeField(default='09:00:00')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_voice', models.TextField(blank=True, help_text="Describe your brand's tone and style. E.g., 'Professional but approachable, uses humor occasionally.'")),
                ('brand_voice_examples', models.JSONField(blank=True, default=list, help_text='Sample posts that represent your brand voice.')),
                ('industry', models.CharField(blank=True, choices=[('saas', 'SaaS / Software'), ('ecommerce', 'E-Commerce'), ('agency', 'Agency / Marketing'), ('creator', 'Creator / Influencer'), ('consulting', 'Consulting / Professional Services'), ('nonprofit', 'Nonprofit'), ('education', 'Education'), ('health', 'Health & Wellness'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list, help_text='Social media goals. E.g., ["Grow followers", "Drive traffic", "Generate leads"]')),
                ('target_audience', models.TextField(blank=True, help_text='Describe your target audience.')),
                ('content_pillars', models.JSONField(blank=True, default=list, help_text='Main topics/themes for content.')),
                ('posting_frequency', models.PositiveIntegerField(default=5, help_text='Target posts per week.')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('agency', 'Agency')], default='starter', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('auto_approve_posts', models.BooleanField(default=False, help_text='If True, agents can publish without approval.')),
                ('auto_engage', models.BooleanField(default=False, help_text='If True, engage agent can respond to comments automatically.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
