# Generated by Django 5.1.15 on 2026-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='Kenyan phone number for M-Pesa payments (254XXXXXXXXX)', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_provider',
            field=models.CharField(choices=[('none', 'None'), ('stripe', 'Stripe'), ('mpesa', 'M-Pesa')], default='none', max_length=20),
        ),
    ]
