# Generated by Django 5.1.15 on 2026-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_brand_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brand_colors',
            field=models.JSONField(blank=True, default=list, help_text="Brand color hex codes. E.g., ['#FF5733', '#1A1A2E', '#FFFFFF']"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brand_logo_url',
            field=models.URLField(blank=True, help_text='Public URL to brand logo for overlay on graphics.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visual_style',
            field=models.CharField(choices=[('photography', 'Photography / Real Photos'), ('illustration', 'Illustrations / Drawn Art'), ('flat_design', 'Flat Design / Minimal'), ('3d_render', '3D Renders'), ('collage', 'Collage / Mixed Media'), ('abstract', 'Abstract / Artistic'), ('corporate', 'Corporate / Clean'), ('vibrant', 'Vibrant / Colorful'), ('dark_moody', 'Dark / Moody'), ('auto', 'Let AI Decide')], default='auto', help_text='Preferred visual style for AI-generated images.', max_length=30),
        ),
    ]
