# Generated by Django 5.1.15 on 2026-04-06 11:15

import apps.platforms.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_brand_colors_userprofile_brand_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mpesa_phone',
            field=apps.platforms.encryption.EncryptedTokenField(blank=True, help_text='Kenyan phone number for M-Pesa payments (254XXXXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=apps.platforms.encryption.EncryptedTokenField(blank=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['subscription_status', 'plan'], name='accounts_us_subscri_be6201_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['payment_provider', 'subscription_status'], name='accounts_us_payment_9af073_idx'),
        ),
    ]
