# Generated by Django 5.1.15 on 2026-04-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cta_email',
            field=models.EmailField(blank=True, help_text='Email address for email CTAs.', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cta_phone',
            field=models.CharField(blank=True, help_text='Phone number for phone CTAs.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cta_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for WhatsApp CTAs.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_cta_type',
            field=models.CharField(choices=[('none', 'No CTA'), ('link', 'Link / URL'), ('phone', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('kova_link', 'Kova Link Page')], default='none', help_text='Default CTA type for new posts.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_cta_url',
            field=models.CharField(blank=True, help_text='Default CTA destination URL.', max_length=500),
        ),
    ]
