# Generated by Django 5.1.15 on 2026-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_emergency_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pixel_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for Kova Pixel website tracking. Generated on first access.', max_length=64, null=True, unique=True),
        ),
    ]
