# Generated by Django 5.1.15 on 2026-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_pixel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Kenyan phone number (07xx, 01xx, 02xx). Multiple users can share a number.', max_length=15),
        ),
    ]
