# Generated by Django 5.1.15 on 2026-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry_other',
            field=models.CharField(blank=True, default='', help_text="Custom industry name when 'Other' is selected.", max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('saas', 'SaaS / Software'), ('ecommerce', 'E-Commerce'), ('agency', 'Agency / Marketing'), ('creator', 'Creator / Influencer'), ('consulting', 'Consulting / Professional Services'), ('nonprofit', 'Nonprofit'), ('education', 'Education'), ('health', 'Health & Wellness'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('food_restaurant', 'Food & Restaurant'), ('wholesale_retail', 'Wholesale & Retail'), ('fashion_beauty', 'Fashion & Beauty'), ('travel_tourism', 'Travel & Tourism'), ('media_entertainment', 'Media & Entertainment'), ('agriculture', 'Agriculture'), ('logistics_transport', 'Logistics & Transport'), ('construction', 'Construction & Manufacturing'), ('legal', 'Legal Services'), ('other', 'Other')], max_length=30),
        ),
    ]
