# Generated by Django 5.1.15 on 2026-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_industry_categories_and_other_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_intelligence_started_at',
            field=models.DateTimeField(blank=True, help_text='Dispatch time of run_onboarding_intelligence. Used by the completion screen to detect stuck polling.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step_timestamps',
            field=models.JSONField(blank=True, default=dict, help_text='First-hit ISO timestamp per onboarding step. Keys: step_1_completed, step_2_completed, step_3_completed, step_4_completed, intelligence_started, intelligence_completed.'),
        ),
    ]
