# Generated by Django 5.1.15 on 2026-05-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_adapt_v2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='page_active',
            field=models.BooleanField(default=True, help_text='Whether the public Kova Link Page is visible.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='page_headline',
            field=models.CharField(blank=True, help_text='One-line tagline shown on the public page.', max_length=160),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='page_slug',
            field=models.SlugField(blank=True, help_text='Public slug for the Kova Link Page (/p/<slug>/). Auto-set to username.', max_length=60, null=True, unique=True),
        ),
    ]
