# Generated by Django 5.1.15 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userprofile_photoroom_brand_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='autopilot_enabled',
            field=models.BooleanField(default=False, help_text='If True, Kova prepares a weekly content plan preview every Monday. You review and approve the strategy before posts are generated.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commerce_autopilot',
            field=models.BooleanField(default=False, help_text='Snap a photo only — AI names, prices, creates posts, and publishes your catalog.', verbose_name='Commerce Autopilot'),
        ),
    ]
