# Generated by Django 5.1.6 on 2026-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_campaign_addon_bonus_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buy_triggers',
            field=models.TextField(blank=True, help_text='What makes customers decide to buy / why they choose this business over others. Customer DNA.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='common_questions',
            field=models.JSONField(blank=True, default=list, help_text="Frequently asked customer questions. Grounds the AI Salesperson. E.g., ['Do you deliver?', 'What are your prices?']"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_problems',
            field=models.TextField(blank=True, help_text='The problems the ideal customer is trying to solve. Customer DNA.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='founder_story',
            field=models.TextField(blank=True, help_text='Why the founder started this business. The origin story that makes campaigns authentic. Brand DNA.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='success_vision',
            field=models.TextField(blank=True, help_text="What success looks like one year from now, in the owner's own words. E.g., 'Double revenue', 'Sell nationwide'. Growth DNA."),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_model',
            field=models.CharField(blank=True, choices=[('product', 'Product business'), ('service', 'Service business'), ('digital', 'Digital products'), ('professional', 'Professional / portfolio'), ('multiple', 'Multiple of these')], default='', help_text='How the business makes money — drives onboarding, the Business Hub layout, and default workflows.', max_length=20),
        ),
    ]
