# Generated by Django 5.1.15 on 2026-04-16 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0015_post_user_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(help_text='Date of the event (or start date)')),
                ('end_date', models.DateField(blank=True, help_text='End date for multi-day events', null=True)),
                ('event_type', models.CharField(choices=[('national_holiday', 'National Holiday'), ('cultural', 'Cultural Event'), ('sports', 'Sports Event'), ('political', 'Political Event'), ('religious', 'Religious Holiday'), ('campus', 'Campus / Youth Event'), ('music', 'Music / Entertainment'), ('commercial', 'Commercial / Business')], db_index=True, max_length=20)),
                ('meme_potential', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('sensitivity', models.CharField(choices=[('safe', 'Safe — universally fine'), ('moderate', 'Moderate — be thoughtful'), ('sensitive', 'Sensitive — tread carefully'), ('avoid', "Avoid — don't meme this")], default='safe', max_length=10)),
                ('annual', models.BooleanField(default=True, help_text='Does this event repeat every year?')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for AI context')),
                ('meme_angles', models.JSONField(blank=True, default=list, help_text="Suggested meme angles for this event, e.g., ['traffic humor', 'family gatherings']")),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'event_type'], name='memes_kenya_date_ce082c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable meme discovery and adaptation for this user')),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative — only universally safe memes'), ('moderate', 'Moderate — some edginess OK'), ('bold', 'Bold — push boundaries (but still brand-safe)')], default='moderate', max_length=15)),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text="Meme categories this user wants, e.g., ['social', 'business', 'food']")),
                ('excluded_categories', models.JSONField(blank=True, default=list, help_text="Categories to never show, e.g., ['political']")),
                ('preferred_humor_types', models.JSONField(blank=True, default=list, help_text="Humor types this user likes, e.g., ['relatable', 'wordplay']")),
                ('max_memes_per_week', models.PositiveIntegerField(default=5, help_text='Maximum meme posts per week')),
                ('auto_queue', models.BooleanField(default=False, help_text='Automatically queue approved adaptations to the content pipeline')),
                ('preferred_platforms', models.JSONField(blank=True, default=list, help_text='Platforms for meme posts, e.g., ["twitter", "instagram"]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meme_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meme preferences',
            },
        ),
        migrations.CreateModel(
            name='TrendingMeme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short name for the meme/trend', max_length=255)),
                ('description', models.TextField(help_text="What this meme is about and why it's trending")),
                ('format_description', models.TextField(help_text="The reusable FORMAT of the meme — the template others can adapt. E.g., 'Top text: expectation. Bottom text: reality with a twist.'")),
                ('example_text', models.TextField(blank=True, help_text='An example of this meme in the wild (the original or a popular version)')),
                ('image_description', models.TextField(blank=True, help_text="Description of the visual component if it's an image meme")),
                ('category', models.CharField(choices=[('social', 'Social / Lifestyle'), ('political', 'Political'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('business', 'Business / Finance'), ('tech', 'Tech'), ('food', 'Food / Culture'), ('music', 'Music'), ('education', 'Education'), ('general', 'General Humor')], db_index=True, default='general', max_length=20)),
                ('humor_type', models.CharField(choices=[('observational', 'Observational'), ('satirical', 'Satirical'), ('absurd', 'Absurd / Surreal'), ('wordplay', 'Wordplay / Puns'), ('situational', 'Situational'), ('relatable', 'Relatable / Everyday'), ('self_deprecating', 'Self-Deprecating'), ('reaction', 'Reaction / Response')], default='relatable', max_length=20)),
                ('source_platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('cross_platform', 'Cross-Platform')], default='cross_platform', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Original source or example URL')),
                ('virality_score', models.PositiveIntegerField(default=0, help_text="How viral is this? 0=niche, 100=everyone's sharing it")),
                ('brand_safety_score', models.PositiveIntegerField(default=50, help_text='How safe for brands? 0=risky, 100=universally safe')),
                ('cultural_relevance_score', models.PositiveIntegerField(default=50, help_text='How culturally relevant to Kenya? 0=foreign, 100=deeply Kenyan')),
                ('adaptability_score', models.PositiveIntegerField(default=50, help_text='How easy to adapt to different brands? 0=very niche, 100=universal format')),
                ('lifecycle', models.CharField(choices=[('emerging', 'Emerging'), ('trending', 'Trending'), ('peaked', 'Peaked'), ('fading', 'Fading'), ('dead', 'Dead')], db_index=True, default='emerging', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('peak_at', models.DateTimeField(blank=True, help_text='When virality peaked', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Estimated expiry — after this, the meme is stale', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags like 'KOT', 'genZ', 'sheng'")),
                ('related_events', models.JSONField(blank=True, default=list, help_text='Related cultural events or moments driving this meme')),
                ('sensitivity_notes', models.TextField(blank=True, help_text='Warnings about political, cultural, or social sensitivity')),
                ('target_demographics', models.JSONField(blank=True, default=list, help_text="Who this meme resonates with, e.g., ['gen_z', 'nairobi', 'campus']")),
                ('adaptation_count', models.PositiveIntegerField(default=0, help_text='How many brand adaptations created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-virality_score', '-detected_at'],
                'indexes': [models.Index(fields=['lifecycle', '-virality_score'], name='memes_trend_lifecyc_5b74ec_idx'), models.Index(fields=['category', 'lifecycle'], name='memes_trend_categor_a04a99_idx'), models.Index(fields=['-detected_at'], name='memes_trend_detecte_c901aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemeAdaptation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapted_text', models.TextField(help_text='The brand-adapted meme content')),
                ('adapted_caption', models.TextField(blank=True, help_text='Platform caption for the meme post')),
                ('platform_targets', models.JSONField(default=list, help_text='Which platforms to post on, e.g., ["twitter", "instagram"]')),
                ('image_prompt', models.TextField(blank=True, help_text='AI image generation prompt for visual meme (if applicable)')),
                ('brand_relevance_score', models.PositiveIntegerField(default=0, help_text="How relevant is this adaptation to the user's brand? 0-100")),
                ('humor_preserved_score', models.PositiveIntegerField(default=0, help_text='How well does the adaptation preserve the humor? 0-100')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why the AI chose this adaptation angle')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, help_text='The Post created from this adaptation (once approved and queued)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meme_adaptation', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_adaptations', to=settings.AUTH_USER_MODEL)),
                ('trending_meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptations', to='memes.trendingmeme')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='memes_memea_user_id_7b3af8_idx'), models.Index(fields=['user', '-created_at'], name='memes_memea_user_id_cafe7c_idx')],
            },
        ),
    ]
