# Generated by Django 5.1.15 on 2026-04-18 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_voicebrief'),
        ('memes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trend_topic', models.CharField(help_text='The trending topic, hashtag, or event name', max_length=300)),
                ('trend_source', models.CharField(blank=True, choices=[('twitter', 'Twitter/X'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('news', 'News'), ('google', 'Google Trends'), ('meme', 'Meme Engine'), ('kenyan_event', 'Kenyan Event Calendar')], max_length=15)),
                ('trend_context', models.TextField(blank=True, help_text="Why this trend matches this user's industry/audience")),
                ('trend_score', models.PositiveIntegerField(default=0, help_text='Relevance score 0-100 (how well this trend matches the user)')),
                ('urgency_hours', models.PositiveIntegerField(default=6, help_text='Estimated hours before this trend dies — drives notification urgency')),
                ('status', models.CharField(choices=[('detected', 'Trend Detected'), ('generating', 'Generating Content'), ('ready', 'Ready for Approval'), ('approved', 'Approved & Queued'), ('dismissed', 'Dismissed'), ('expired', 'Trend Expired'), ('failed', 'Failed')], db_index=True, default='detected', max_length=15)),
                ('brand_angle', models.TextField(blank=True, help_text="AI's explanation of the brand-safe angle for this trend")),
                ('posts_generated', models.PositiveIntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this trend alert expires (detected_at + urgency_hours)', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('content_seed', models.ForeignKey(blank=True, help_text='ContentSeed with trend-riding posts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_alerts', to='content.contentseed')),
                ('kenyan_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_alerts', to='memes.kenyanevent')),
                ('trending_meme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_alerts', to='memes.trendingmeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='memes_trend_user_id_4b2f5d_idx'), models.Index(fields=['user', '-detected_at'], name='memes_trend_user_id_b76190_idx'), models.Index(fields=['status', 'expires_at'], name='memes_trend_status_bdab0f_idx')],
            },
        ),
    ]
