# Generated by Django 5.1.15 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_memeadaptation_failed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memepreferences',
            name='excluded_categories',
            field=models.JSONField(blank=True, default=list, help_text="Categories to never show, e.g., ['political']"),
        ),
    ]
