# Generated by Django 5.1.15 on 2026-05-16 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_goal_metric_campaign_goal_target'),
        ('content', '0018_alter_post_first_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.SlugField(max_length=12, unique=True)),
                ('label', models.CharField(help_text='Human-readable name. E.g. "Jamhuri flyer", "Door sticker", "Receipt corner".', max_length=200)),
                ('landing_template', models.CharField(choices=[('discount', 'Show a discount'), ('menu', 'Show menu / catalog'), ('booking', 'Book an appointment'), ('follow', 'Follow us on social'), ('custom', 'Custom message')], default='discount', max_length=20)),
                ('landing_payload', models.JSONField(blank=True, default=dict, help_text='Template-specific config. Shapes per template:\n  discount → {discount_pct, valid_until, terms}\n  menu     → {menu_image_url, today_special}\n  booking  → {booking_link, contact_whatsapp}\n  follow   → {instagram_handle, facebook_url}\n  custom   → {headline, body, cta_text, cta_url}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='campaigns.campaign')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA-256 hash of the source IP — for dedup, never stored raw.', max_length=64)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_attribution.qrcode')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkInEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribution_source', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('flyer', 'Flyer / Poster'), ('word_of_mouth', 'Word of mouth'), ('walk_by', 'Walked by / signage'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('attribution_label', models.CharField(blank=True, help_text='Free-text fallback when source=other.', max_length=80)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Optional KES revenue from this walk-in.', max_digits=10, null=True)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_ins', to='qr_attribution.qrcode')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_ins', to='qr_attribution.qrscan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['user', '-created_at'], name='qr_attribut_user_id_9776d3_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['user', 'is_active'], name='qr_attribut_user_id_a54918_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['qr_code', '-scanned_at'], name='qr_attribut_qr_code_ae5d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['visitor_id', '-scanned_at'], name='qr_attribut_visitor_375e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='walkinevent',
            index=models.Index(fields=['user', '-recorded_at'], name='qr_attribut_user_id_6dbef8_idx'),
        ),
        migrations.AddIndex(
            model_name='walkinevent',
            index=models.Index(fields=['user', 'attribution_source', '-recorded_at'], name='qr_attribut_user_id_e2b4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='walkinevent',
            index=models.Index(fields=['qr_code', '-recorded_at'], name='qr_attribut_qr_code_bbac5a_idx'),
        ),
    ]
