# Generated by Django 5.1.15 on 2026-04-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_encrypt_oauth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('creator', 'Creator'), ('page', 'Page'), ('organization', 'Organization')], default='personal', help_text='Type of account: personal, business, creator, page, or organization', max_length=20),
        ),
    ]
