# Generated by Django 5.1.15 on 2026-04-10 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0012_post_cta_text_post_cta_type_post_cta_url_and_more'),
        ('emails', '0005_emailsubscriber_lead_emailsubscriber_source_form_and_more'),
        ('teams', '0003_team_deleted_at_team_is_deleted_alter_team_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objective', models.CharField(choices=[('awareness', 'Brand Awareness'), ('engagement', 'Engagement'), ('traffic', 'Website Traffic'), ('leads', 'Lead Generation'), ('sales', 'Sales / Conversions'), ('launch', 'Product Launch')], default='awareness', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_platforms', models.JSONField(blank=True, default=list, help_text="e.g. ['instagram','twitter','linkedin']")),
                ('target_audience', models.TextField(blank=True, help_text='Description of target audience')),
                ('utm_campaign_tag', models.SlugField(blank=True, help_text='Auto-generated UTM campaign tag', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='teams.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('announcement', 'Announcement'), ('follow_up', 'Follow-up'), ('reminder', 'Reminder')], default='announcement', max_length=20)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_emails', to='campaigns.campaign')),
                ('email_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='emails.emailcampaign')),
            ],
            options={
                'ordering': ['sequence_order', 'created_at'],
                'unique_together': {('campaign', 'email_campaign')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_campaigns',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='campaigns.CampaignEmail', to='emails.emailcampaign'),
        ),
        migrations.CreateModel(
            name='CampaignNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status Change'), ('approval', 'Approval'), ('content_added', 'Content Added')], default='comment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary Content'), ('supporting', 'Supporting'), ('follow_up', 'Follow-up')], default='primary', max_length=20)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_seeds', to='campaigns.campaign')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='content.contentseed')),
            ],
            options={
                'ordering': ['sequence_order', 'created_at'],
                'unique_together': {('campaign', 'seed')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_seeds',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='campaigns.CampaignSeed', to='content.contentseed'),
        ),
    ]
