# Generated by Django 5.1.15 on 2026-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='goal_metric',
            field=models.CharField(choices=[('none', 'No Goal'), ('impressions', 'Impressions'), ('reach', 'Reach'), ('clicks', 'Link Clicks'), ('leads', 'Leads'), ('sales', 'Sales'), ('revenue', 'Revenue (KES)'), ('engagement', 'Engagements')], default='none', help_text='What KPI are you targeting?', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target number to hit.', max_digits=12, null=True),
        ),
    ]
