# Generated by Django 4.2.23 on 2026-06-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_legacy_campaign_app'),
        ('qr_attribution', '0004_remove_legacy_campaign_app'),
        ('content', '0036_remove_legacy_campaign_app'),
        ('campaigns', '0002_campaign_goal_metric_campaign_goal_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignemail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campaignemail',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignemail',
            name='email_campaign',
        ),
        migrations.RemoveField(
            model_name='campaignnote',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignnote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='campaignseed',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campaignseed',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignseed',
            name='seed',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignEmail',
        ),
        migrations.DeleteModel(
            name='CampaignNote',
        ),
        migrations.DeleteModel(
            name='CampaignSeed',
        ),
    ]
