# Generated by Django 5.1.15 on 2026-04-02 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_mpesapayment_billingevent_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('plan_change', 'Plan Change'), ('trial_extension', 'Trial Extension'), ('comp_access', 'Complimentary Access'), ('status_change', 'Status Change'), ('bulk_grant', 'Bulk Grant')], max_length=30)),
                ('previous_plan', models.CharField(blank=True, max_length=20)),
                ('new_plan', models.CharField(blank=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('days_granted', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Why this override was applied')),
                ('batch_id', models.CharField(blank=True, help_text='Groups bulk operations together', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='billing_sub_action_1d4504_idx'), models.Index(fields=['batch_id'], name='billing_sub_batch_i_c71f03_idx')],
            },
        ),
    ]
