# Generated by Django 5.1.15 on 2026-04-07 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_mpesapayment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique code (auto-uppercased)', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, help_text='Internal admin note', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_kes', 'Fixed Amount (KES)'), ('fixed_usd', 'Fixed Amount (USD)')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20 for 20%) or fixed amount', max_digits=10)),
                ('applicable_plans', models.JSONField(blank=True, default=list, help_text='Plan tiers this applies to. Empty list = all plans. e.g. ["growth","pro"]')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Total max redemptions. 0 = unlimited.')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Max redemptions per user.')),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField(help_text='When the code becomes active')),
                ('valid_until', models.DateTimeField(help_text='When the code expires')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_tier', models.CharField(max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.discountcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Jipange / Starter'), ('growth', 'Kazi / Growth'), ('pro', 'Biashara / Pro'), ('agency', 'Wakala / Agency')], max_length=20, unique=True)),
                ('price_kes', models.PositiveIntegerField(help_text='Monthly price in KES')),
                ('price_usd', models.PositiveIntegerField(help_text='Monthly price in USD')),
                ('is_active', models.BooleanField(default=True, help_text='When inactive, falls back to hardcoded PLAN_LIMITS price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Price',
                'verbose_name_plural': 'Plan Prices',
            },
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code'], name='billing_dis_code_a1334f_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='billing_dis_is_acti_890a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='discountredemption',
            index=models.Index(fields=['discount_code', 'user'], name='billing_dis_discoun_1014f5_idx'),
        ),
    ]
