# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_agencysalesinquiry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentseedquotalog',
            new_name='billing_con_user_id_ccb309_idx',
            old_name='billing_csq_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contentseedquotalog',
            new_name='billing_con_action_944e3c_idx',
            old_name='billing_csq_action_created_idx',
        ),
    ]
