# Generated by Django 5.1.15 on 2026-04-04 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('role_changed', 'Role Changed'), ('post_created', 'Post Created'), ('post_published', 'Post Published'), ('post_approved', 'Post Approved'), ('brand_created', 'Brand Created'), ('brand_updated', 'Brand Updated'), ('seed_submitted', 'Seed Submitted'), ('invitation_sent', 'Invitation Sent')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Team activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand or client name', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('brand_voice', models.TextField(blank=True, help_text="Describe this brand's tone and style.")),
                ('brand_voice_examples', models.JSONField(blank=True, default=list, help_text="Sample posts that represent this brand's voice.")),
                ('industry', models.CharField(blank=True, max_length=30)),
                ('website_url', models.URLField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('content_pillars', models.JSONField(blank=True, default=list, help_text="Main topics/themes for this brand's content.")),
                ('goals', models.JSONField(blank=True, default=list, help_text='Social media goals for this brand.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='teams.team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'slug')},
            },
        ),
    ]
