# Generated by Django 5.1.15 on 2026-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_batch_strategy_and_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_dna',
            field=models.JSONField(blank=True, default=dict, help_text='Content attributes for analysis. E.g. {"format": "question", "tone": "inspirational", "topic": "success_story", "has_cta": true, "has_stats": true, "length": "short"}'),
        ),
    ]
