# Generated by Django 5.1.15 on 2026-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_content_dna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentseed',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Posts Generated'), ('failed', 'Failed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing...'), ('published', 'Published'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
    ]
