# Generated by Django 5.1.15 on 2026-04-04 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_post_ai_original_text_post_edit_distance_ratio_and_more'),
        ('teams', '0002_teamactivity_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentseed',
            name='brand',
            field=models.ForeignKey(blank=True, help_text="Brand this content is for. Null = user's default brand voice.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_seeds', to='teams.brand'),
        ),
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(blank=True, help_text="Brand this post belongs to. Null = user's default brand voice.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='teams.brand'),
        ),
    ]
