# Generated by Django 5.1.15 on 2026-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentseed_brand_post_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_status',
            field=models.CharField(choices=[('none', 'No media'), ('pending', 'Pending generation'), ('generated', 'AI-generated'), ('uploaded', 'Manually uploaded'), ('failed', 'Generation failed')], default='none', help_text='Tracks whether AI image generation succeeded, failed, or was skipped.', max_length=20),
        ),
    ]
