# Generated by Django 5.1.15 on 2026-04-06 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_post_media_status'),
        ('platforms', '0006_socialaccount_platforms_s_user_id_479427_idx_and_more'),
        ('teams', '0003_team_deleted_at_team_is_deleted_alter_team_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_text', models.TextField()),
                ('source', models.CharField(choices=[('user_edit', 'User Edit'), ('regeneration', 'AI Regeneration'), ('creation', 'Created')], default='user_edit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='abtest',
            name='platform',
            field=models.CharField(blank=True, db_index=True, help_text='Denormalized platform name — preserved when social_account is disconnected.', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(blank=True, db_index=True, help_text='Denormalized platform name — preserved when social_account is disconnected.', max_length=20),
        ),
        migrations.AlterField(
            model_name='abtest',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='platforms.socialaccount'),
        ),
        migrations.AlterField(
            model_name='post',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='platforms.socialaccount'),
        ),
        migrations.AddIndex(
            model_name='contentseed',
            index=models.Index(fields=['user', 'status', '-created_at'], name='content_con_user_id_0b559b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentseed',
            index=models.Index(fields=['user', '-created_at'], name='content_con_user_id_e8bd96_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'status', '-created_at'], name='content_pos_user_id_4f0925_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['social_account', 'status', '-scheduled_at'], name='content_pos_social__1b9f81_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-scheduled_at'], name='content_pos_user_id_e46369_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'media_status'], name='content_pos_user_id_1363cb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['seed', 'status'], name='content_pos_seed_id_b09e88_idx'),
        ),
        migrations.AddField(
            model_name='postversion',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postversion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.post'),
        ),
        migrations.AlterUniqueTogether(
            name='postversion',
            unique_together={('post', 'version_number')},
        ),
    ]
