# Generated by Django 5.1.15 on 2026-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_postversion_abtest_platform_post_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_prompt',
            field=models.TextField(blank=True, help_text='AI image prompt used for generation. Stored for retry capability.'),
        ),
    ]
