# Generated by Django 5.1.15 on 2026-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_post_cta_text_post_cta_type_post_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visual_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Visual generation details: {"image_prompt": "...", "template": "...", "model": "...", "provider": "..."}'),
        ),
        migrations.AddField(
            model_name='post',
            name='visual_strategy',
            field=models.CharField(choices=[('none', 'No visual'), ('ai_photo', 'AI-generated photo'), ('quote_card', 'Quote card'), ('tip_graphic', 'Tip graphic'), ('stat_highlight', 'Stat highlight'), ('cta_banner', 'CTA banner'), ('carousel', 'Carousel'), ('story_graphic', 'Story graphic')], db_index=True, default='none', help_text='Which visual strategy was used for this post. Stored for analytics.', max_length=30),
        ),
    ]
