# Generated by Django 5.1.15 on 2026-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_add_generate_images_to_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '👎 Poor'), (2, '👍 Good'), (3, '🔥 Great')], help_text="User's quality rating of AI-generated content (1=poor, 2=good, 3=great).", null=True),
        ),
    ]
