# Generated by Django 5.1.15 on 2026-05-29 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_post_published_at_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklycontentplan',
            name='unique_user_week_start',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='content_post_user_format_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklycontentplan',
            new_name='content_wee_user_id_245e0e_idx',
            old_name='content_wcp_user_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='weeklycontentplan',
            unique_together={('user', 'week_start')},
        ),
    ]
