# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_system_safety_checks_toggle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentsafetyincident',
            new_name='content_con_review__7adf57_idx',
            old_name='content_con_review__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='contentsafetyincident',
            new_name='content_con_user_id_cc9a9e_idx',
            old_name='content_con_user_id_d4e5f6_idx',
        ),
    ]
