# Generated by Django 4.2.23 on 2026-06-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_marketingcampaign_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicebrief',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The marketing campaign auto-generated from this voice brief', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_briefs', to='content.marketingcampaign'),
        ),
    ]
