# Generated by Django 5.1.15 on 2026-04-08 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KovaPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Page headline, e.g. your brand name', max_length=100)),
                ('slug', models.SlugField(help_text='URL path: kovaagent.com/k/your-slug', max_length=60, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Short description under the title', max_length=300)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile image URL')),
                ('theme', models.CharField(choices=[('minimal', 'Minimal'), ('bold', 'Bold'), ('gradient', 'Gradient'), ('dark', 'Dark'), ('neon', 'Neon'), ('warm', 'Warm')], default='minimal', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Pro plan: custom CSS overrides')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color', max_length=7)),
                ('text_color', models.CharField(default='#111827', help_text='Hex color', max_length=7)),
                ('accent_color', models.CharField(default='#7c3aed', help_text='Hex color for buttons', max_length=7)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('og_image_url', models.URLField(blank=True, help_text='Social share image')),
                ('is_published', models.BooleanField(default=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kova_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KovaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('url', 'External URL'), ('social', 'Social Profile'), ('email', 'Email'), ('phone', 'Phone / WhatsApp'), ('header', 'Section Header')], default='url', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, help_text='Required for URL and Social types')),
                ('icon', models.CharField(blank=True, help_text="Icon name, e.g. 'instagram', 'globe'", max_length=50)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlighted with accent color')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.kovapage')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KovaForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('contact', 'Contact Form'), ('newsletter', 'Newsletter Signup'), ('waitlist', 'Waitlist / Interest'), ('booking', 'Booking Request'), ('custom', 'Custom Form')], default='contact', max_length=20)),
                ('title', models.CharField(default='Get in Touch', max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('button_text', models.CharField(default='Submit', max_length=50)),
                ('success_message', models.CharField(default="Thanks! We'll be in touch.", max_length=200)),
                ('show_name_field', models.BooleanField(default=True)),
                ('show_phone_field', models.BooleanField(default=False)),
                ('show_message_field', models.BooleanField(default=True)),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='List of {"label": "...", "type": "text|select|textarea", "required": bool, "options": [...]}')),
                ('notify_on_submission', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, help_text='Override — defaults to account email', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='links.kovapage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, help_text='ISO country code from GeoIP', max_length=2)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], max_length=10)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.kovalink')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='links.kovapage')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Responses to custom fields')),
                ('referrer', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('page_slug', models.CharField(blank=True, help_text='Which Kova page they were on', max_length=60)),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='links.kovaform')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['form', '-submitted_at'], name='links_forms_form_id_3cc5c5_idx'), models.Index(fields=['email'], name='links_forms_email_bd940d_idx'), models.Index(fields=['is_read', '-submitted_at'], name='links_forms_is_read_6ec22e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kovapage',
            index=models.Index(fields=['user', '-created_at'], name='links_kovap_user_id_d84c33_idx'),
        ),
        migrations.AddIndex(
            model_name='kovapage',
            index=models.Index(fields=['slug'], name='links_kovap_slug_81e2da_idx'),
        ),
        migrations.AddIndex(
            model_name='kovalink',
            index=models.Index(fields=['page', 'order'], name='links_koval_page_id_9e1c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['link', '-clicked_at'], name='links_linkc_link_id_1945c0_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page', '-date'], name='links_pagev_page_id_bd44a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageview',
            unique_together={('page', 'date')},
        ),
    ]
