# Generated by Django 5.1.15 on 2026-04-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_marketplacepartner_marketplaceselleraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepartner',
            name='enrich_descriptions',
            field=models.BooleanField(default=True, help_text='Auto-append marketplace-specific data (condition, variants, specs) to product descriptions so AI generates richer content.'),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='seller_data_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Maps marketplace seller fields to seller_metadata keys. E.g. {"business_name": "shop_name", "seller_tier": "tier", "campus_codes": "locations"}'),
        ),
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='business_name',
            field=models.CharField(blank=True, help_text="Seller's shop/business name on the marketplace", max_length=200),
        ),
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='business_url',
            field=models.URLField(blank=True, help_text="Direct URL to seller's store on the marketplace"),
        ),
        migrations.AlterField(
            model_name='marketplaceselleraccount',
            name='seller_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Marketplace-specific seller info. Examples:\n{"shop_name": "Jane Electronics", "shop_url": "https://jumia.co.ke/jane-electronics"}\n{"seller_tier": "gold", "store_rating": 4.7, "campus_codes": ["USIU", "KU"]}\n{"location": "Nairobi", "category": "Electronics", "is_approved": true, "delivery_zones": ["same_campus", "same_city"]}'),
        ),
    ]
