# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_referral_payout_campus'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralclick',
            new_name='partners_re_referra_56cdb7_idx',
            old_name='partners_re_referra_idx',
        ),
        migrations.RenameIndex(
            model_name='referralclick',
            new_name='partners_re_partner_930f77_idx',
            old_name='partners_re_partner_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='partners_we_marketp_b84e19_idx',
            old_name='partners_we_marketp_8a1f2d_idx',
        ),
    ]
