from django.urls import path

from apps.core.admin_dashboard.views import (
    agents,
    analytics,
    billing,
    blog,
    content,
    content_safety,
    costs,
    emails,
    feature_usage,
    help,
    innovations,
    leads,
    llm,
    logs,
    notifications,
    onboarding,
    operations,
    ops,
    overview,
    partials,
    photoroom,
    pilot,
    pixel,
    platforms,
    products,
    reel_music,
    revenue,
    sales_inquiries,
    search,
    seed_quota,
    system,
    system_maps,
    user_health,
    users,
    whatsapp,
)

app_name = "admin_dashboard"

# V1 admin: core ops only. Bookings/reviews/QR/partners/teams/AB/nurture/
# engage UI routes removed (templates deleted). Apps remain installed.

urlpatterns = [
    path("", overview.overview, name="overview"),
    path("search/", search.global_search, name="global_search"),
    path("search/suggest/", search.search_suggest, name="global_search_suggest"),
    path("feature-usage/", feature_usage.feature_usage, name="feature_usage"),
    path("pilot/", pilot.pilot_overview, name="pilot_overview"),

    path("users/", users.user_list, name="user_list"),
    path("users/export/", users.user_export_csv, name="user_export"),
    path("users/<uuid:pk>/", users.user_detail, name="user_detail"),
    path("users/<uuid:pk>/usage/", users.user_usage_detail, name="user_usage_detail"),
    path("users/<uuid:pk>/change-plan/", users.user_change_plan, name="user_change_plan"),
    path("users/<uuid:pk>/toggle-staff/", users.user_toggle_staff, name="user_toggle_staff"),
    path("users/<uuid:pk>/toggle-active/", users.user_toggle_active, name="user_toggle_active"),
    path("users/<uuid:pk>/delete/", users.user_delete, name="user_delete"),
    path("users/health/", user_health.user_health, name="user_health"),
    path("users/onboarding-funnel/", onboarding.onboarding_funnel, name="onboarding_funnel"),

    path("operations/", operations.operations_overview, name="operations_overview"),
    path("ops/celery/", ops.celery_health, name="ops_celery"),

    path("reel-music/", reel_music.reel_music_manage, name="reel_music_manage"),
    path("reel-music/upload/", reel_music.reel_music_upload, name="reel_music_upload"),
    path("reel-music/<str:track_id>/replace/", reel_music.reel_music_replace, name="reel_music_replace"),
    path("reel-music/<str:track_id>/delete/", reel_music.reel_music_delete, name="reel_music_delete"),
    path("reel-music/<str:track_id>/preview/", reel_music.reel_music_preview, name="reel_music_preview"),

    path("leads/", leads.leads_overview, name="leads_overview"),
    path("leads/list/", leads.lead_list, name="lead_list"),

    path("content/", content.content_overview, name="content_overview"),
    path("content/posts/", content.post_list, name="post_list"),
    path("content/posts/<uuid:pk>/", content.post_detail, name="post_detail_admin"),
    path("content/seeds/", content.seed_list, name="seed_list"),
    path("content/seed-quotas/", seed_quota.seed_quota_hub, name="seed_quota_hub"),
    path("content/seed-quotas/log/", seed_quota.seed_quota_log, name="seed_quota_log"),
    path("users/<uuid:pk>/seed-quota/", seed_quota.seed_quota_action, name="seed_quota_action"),
    path("content/failed/", content.failed_content, name="failed_content"),

    path("content-safety/", content_safety.content_safety_overview, name="content_safety_overview"),
    path("content-safety/review/", content_safety.content_safety_review, name="content_safety_review"),
    path("content-safety/review/<uuid:pk>/", content_safety.content_safety_incident_detail, name="content_safety_incident_detail"),
    path("content-safety/global-toggle/", content_safety.content_safety_global_toggle, name="content_safety_global_toggle"),
    path("content-safety/checks-toggle/", content_safety.content_safety_checks_toggle, name="content_safety_checks_toggle"),

    path("agents/", agents.agent_overview, name="agent_overview"),
    path("agents/log/", agents.agent_log, name="agent_log"),
    path("agents/tokens/", agents.token_economics, name="token_economics"),

    path("llm/", llm.llm_overview, name="llm_overview"),
    path("llm/update/", llm.llm_update_config, name="llm_update_config"),
    path("llm/task-model/", llm.llm_update_task_model, name="llm_update_task_model"),
    path("llm/plan-models/", llm.llm_update_plan_models, name="llm_update_plan_models"),
    path("llm/rate-limits/", llm.llm_update_rate_limits, name="llm_update_rate_limits"),
    path("llm/apply-preset/", llm.llm_apply_preset, name="llm_apply_preset"),
    path("llm/image-config/", llm.llm_update_image_config, name="llm_update_image_config"),
    path("llm/image-plan-models/", llm.llm_update_image_plan_models, name="llm_update_image_plan_models"),

    path("platforms/", platforms.platform_overview, name="platform_overview"),
    path("platforms/accounts/", platforms.platform_accounts, name="platform_accounts"),

    path("billing/", billing.billing_overview, name="billing_overview"),
    path("billing/payments/", billing.payment_list, name="payment_list"),
    path("billing/events/", billing.billing_events, name="billing_events"),
    path("billing/subscriptions/", billing.subscription_management, name="subscription_management"),
    path("billing/subscriptions/action/", billing.subscription_action, name="subscription_action"),
    path("billing/bulk-grant/", billing.bulk_grant, name="bulk_grant"),
    path("billing/overrides/", billing.override_log, name="override_log"),
    path("billing/pricing/", billing.plan_pricing, name="plan_pricing"),
    path("billing/pricing/update/", billing.plan_pricing_update, name="plan_pricing_update"),
    path("billing/discounts/", billing.discount_list, name="discount_list"),
    path("billing/discounts/create/", billing.discount_create, name="discount_create"),
    path("billing/discounts/<uuid:pk>/edit/", billing.discount_edit, name="discount_edit"),
    path("billing/discounts/<uuid:pk>/toggle/", billing.discount_toggle, name="discount_toggle"),
    path("billing/sales-inquiries/", sales_inquiries.sales_inquiry_list, name="sales_inquiry_list"),
    path("billing/sales-inquiries/<uuid:pk>/", sales_inquiries.sales_inquiry_detail, name="sales_inquiry_detail"),

    path("costs/", costs.cost_overview, name="cost_overview"),
    path("costs/calculator/", costs.cost_calculator, name="cost_calculator"),

    path("_partials/stat-cards/", partials.partial_stat_cards, name="partial_stat_cards"),
    path("_partials/activity-feed/", partials.partial_activity_feed, name="partial_activity_feed"),
    path("_partials/agent-health/", partials.partial_agent_health, name="partial_agent_health"),

    path("system/", system.system_health, name="system_health"),
    path("system/errors/", system.error_log, name="error_log"),

    path("logs/", logs.activity_log, name="activity_log"),
    path("logs/export/", logs.log_export_csv, name="log_export"),

    path("analytics/", analytics.analytics_overview, name="analytics_overview"),
    path("analytics/content-dna/", analytics.content_dna_analysis, name="content_dna_analysis"),

    path("revenue/", revenue.revenue_overview, name="revenue_overview"),
    path("revenue/conversions/", revenue.conversion_list, name="revenue_conversions"),
    path("revenue/shopify/", revenue.shopify_stores_list, name="shopify_stores"),
    path("revenue/shopify/<uuid:pk>/toggle/", revenue.shopify_store_toggle, name="shopify_store_toggle"),
    path("revenue/journeys/", revenue.journey_list, name="revenue_journeys"),

    path("pixel/", pixel.pixel_overview, name="pixel_overview"),
    path("pixel/events/", pixel.pixel_events, name="pixel_events"),
    path("pixel/users/", pixel.pixel_users, name="pixel_users"),

    path("emails/", emails.email_overview, name="emails"),
    path("emails/log/", emails.email_log, name="email_log"),
    path("emails/<uuid:pk>/", emails.email_detail, name="email_detail"),
    path("emails/test/", emails.send_test_email, name="email_test"),

    path("help/", help.help_overview, name="help_overview"),
    path("help/articles/", help.help_article_views, name="help_article_views"),
    path("help/log/", help.help_view_log, name="help_view_log"),

    path("system-maps/", system_maps.system_maps_index, name="system_maps"),
    path("system-maps/print/", system_maps.system_maps_print, name="system_maps_print"),
    path("system-maps/<slug:slug>/", system_maps.system_map_detail, name="system_map"),

    path("blog/", blog.blog_studio, name="blog_studio"),
    path("blog/draft-next/", blog.blog_draft_next, name="blog_draft_next"),
    path("blog/suggest-topics/", blog.blog_suggest_topics, name="blog_suggest_topics"),
    path("blog/articles/<uuid:pk>/", blog.blog_article_review, name="blog_article_review"),
    path("blog/articles/<uuid:pk>/publish/", blog.blog_article_publish, name="blog_article_publish"),
    path("blog/articles/<uuid:pk>/unpublish/", blog.blog_article_unpublish, name="blog_article_unpublish"),
    path("blog/articles/<uuid:pk>/delete/", blog.blog_article_delete, name="blog_article_delete"),
    path("blog/topics/<uuid:pk>/draft/", blog.blog_draft_topic, name="blog_draft_topic"),
    path("blog/topics/<uuid:pk>/skip/", blog.blog_skip_topic, name="blog_skip_topic"),

    path("commerce/", products.commerce_overview, name="commerce_overview"),
    path("commerce/catalog/", products.commerce_catalog, name="commerce_catalog"),
    path("commerce/catalog/<uuid:pk>/", products.commerce_product_detail, name="commerce_product_detail"),
    path("commerce/shops/", products.commerce_shops, name="commerce_shops"),
    path("commerce/payments/", products.commerce_payments, name="commerce_payments"),
    path("commerce/integrations/", products.commerce_integrations, name="commerce_integrations"),
    path("commerce/alerts/", products.commerce_stock_alerts, name="commerce_stock_alerts"),
    path("commerce/stock/", products.commerce_stock_updates, name="commerce_stock_updates"),
    path("commerce/photoroom/", photoroom.photoroom_config, name="commerce_photoroom"),
    path("products/", products.commerce_overview, name="products_overview"),
    path("products/list/", products.commerce_catalog, name="admin_product_list"),
    path("products/alerts/", products.commerce_stock_alerts, name="admin_stock_alerts"),
    path("products/updates/", products.commerce_stock_updates, name="admin_stock_updates"),

    path("notifications/", notifications.notifications_overview, name="notifications_overview"),
    path("notifications/log/", notifications.notification_log, name="notification_log"),

    path("whatsapp/", whatsapp.whatsapp_overview, name="whatsapp_overview"),
    path("whatsapp/conversations/", whatsapp.whatsapp_conversations, name="whatsapp_conversations"),
    path("whatsapp/templates/", whatsapp.whatsapp_templates, name="whatsapp_templates"),
    path("whatsapp/commerce-receipts/", whatsapp.whatsapp_commerce_receipts, name="whatsapp_commerce_receipts"),
    path("whatsapp/brief-delivery/", whatsapp.whatsapp_brief_delivery, name="whatsapp_brief_delivery"),

    path("innovations/", innovations.innovations_overview, name="innovations_overview"),
    path("innovations/voice/", innovations.voice_brief_list, name="voice_brief_list"),
    path("innovations/voice/<uuid:pk>/", innovations.voice_brief_detail, name="voice_brief_detail"),
    path("innovations/screenshots/", innovations.screenshot_list, name="screenshot_list"),
    path("innovations/screenshots/<uuid:pk>/", innovations.screenshot_detail, name="screenshot_detail"),
    path("innovations/restock/", innovations.restock_scan_list, name="restock_scan_list"),
    path("innovations/restock/<uuid:pk>/", innovations.restock_scan_detail, name="restock_scan_detail"),
    path("innovations/trends/", innovations.trend_alert_list, name="trend_alert_list"),
    path("innovations/trends/<uuid:pk>/", innovations.trend_alert_detail, name="trend_alert_detail"),
    path("innovations/recycle/", innovations.recycle_list, name="recycle_list"),
    path("innovations/recycle/<uuid:pk>/", innovations.recycle_detail, name="recycle_detail"),
]
