# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attribution', '0002_walkin_customer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkinevent',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Optional name captured at cashier.', max_length=200),
        ),
        migrations.AlterField(
            model_name='walkinevent',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Optional phone — creates a Lead when set.', max_length=20),
        ),
    ]
