# Generated by Django 4.2.23 on 2026-06-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_legacy_campaign_app'),
        ('qr_attribution', '0003_alter_walkinevent_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='content.marketingcampaign'),
        ),
    ]
