# Generated by Django 5.1.15 on 2026-04-15 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0007_alter_socialaccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_wa_id', models.CharField(db_index=True, help_text='WhatsApp ID (usually the phone number without +)', max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_name', models.CharField(blank=True, help_text='Push name from WhatsApp', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='active', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('sheng', 'Sheng'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('ai_handling', models.BooleanField(default=True, help_text='Is AI currently handling this conversation?')),
                ('window_expires_at', models.DateTimeField(blank=True, help_text='When the 24-hour service window expires. After this, only templates allowed.', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Running average sentiment (-1 negative to +1 positive)', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Customer segments / tags')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Conversation context for AI (product interests, past questions, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='platforms.socialaccount')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (lowercase, underscores only — Meta requirement)', max_length=512)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('header_type', models.CharField(choices=[('none', 'None'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='none', max_length=20)),
                ('header_text', models.CharField(blank=True, help_text='Header text (if header_type=text)', max_length=60)),
                ('header_media_url', models.URLField(blank=True, help_text='Header media URL (if image/video/document)')),
                ('body_text', models.TextField(help_text='Template body with {{1}}, {{2}} variable slots')),
                ('footer_text', models.CharField(blank=True, max_length=60)),
                ('buttons', models.JSONField(blank=True, default=list, help_text='Quick reply or CTA buttons [{type, text, url/phone_number}]')),
                ('meta_template_id', models.CharField(blank=True, help_text='Template ID from Meta', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('performance_data', models.JSONField(blank=True, default=dict, help_text='Tracked: open_rate, reply_rate, block_rate, send_count')),
                ('created_by_ai', models.BooleanField(default=False)),
                ('ai_prompt_used', models.TextField(blank=True, help_text='The natural language prompt that generated this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='platforms.socialaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive'), ('template', 'Template'), ('reaction', 'Reaction'), ('order', 'Order')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content or caption')),
                ('media_url', models.URLField(blank=True, help_text='Media URL (image, video, audio, document)')),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('interactive_data', models.JSONField(blank=True, default=dict, help_text='Button clicks, list selections, flow responses')),
                ('wamid', models.CharField(blank=True, db_index=True, help_text='WhatsApp message ID (wamid) for status tracking', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence when auto-replied (0.0 to 1.0)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('segment', models.JSONField(blank=True, default=dict, help_text='Targeting criteria: {tags: [], languages: [], last_active_days: N}')),
                ('recipient_phones', models.JSONField(blank=True, default=list, help_text='Resolved list of contact wa_ids to send to')),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text="Variable mappings: {1: 'field_name', 2: 'field_name'}")),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('per_contact_timing', models.BooleanField(default=False, help_text='Let Adapt Agent optimize send time per recipient')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('replied_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_broadcasts', to='platforms.socialaccount')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['social_account', 'status', '-last_message_at'], name='whatsapp_wh_social__b4e850_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappconversation',
            unique_together={('social_account', 'contact_wa_id')},
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['social_account', 'status'], name='whatsapp_wh_social__76b22a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsapptemplate',
            unique_together={('social_account', 'name', 'language')},
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='whatsapp_wh_convers_162467_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['wamid'], name='whatsapp_wh_wamid_7ef16d_idx'),
        ),
    ]
