# Generated by Django 5.1.6 on 2026-07-02 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_statustemplate_broadcastsequence_whatsappchannel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_phone', models.CharField(db_index=True, max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer memories',
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='whatsapp_cu_user_id_40420b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'contact_phone'), name='unique_customer_memory_per_contact')],
            },
        ),
    ]
