import uuid
from django.db import models


class PostMetric(models.Model):
    """Engagement metrics for a published post."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.OneToOneField("content.Post", on_delete=models.CASCADE, related_name="metrics")
    impressions = models.PositiveIntegerField(default=0)
    reach = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    comments = models.PositiveIntegerField(default=0)
    shares = models.PositiveIntegerField(default=0)
    saves = models.PositiveIntegerField(default=0)
    clicks = models.PositiveIntegerField(default=0)
    engagement_rate = models.FloatField(null=True, blank=True)
    fetched_at = models.DateTimeField(auto_now=True)

    # Intelligence: predicted vs. actual comparison
    predicted_score = models.FloatField(
        null=True, blank=True,
        help_text="Snapshot of Post.predicted_engagement_score at publish time.",
    )
    actual_score = models.FloatField(
        null=True, blank=True,
        help_text="Normalized actual engagement score (0-100) calculated from real metrics.",
    )
    prediction_error = models.FloatField(
        null=True, blank=True,
        help_text="actual_score - predicted_score. Positive = underestimated, negative = overestimated.",
    )
    prediction_validated_at = models.DateTimeField(
        null=True, blank=True,
        help_text="When the prediction was compared against actuals.",
    )

    def __str__(self):
        return f"Metrics for {self.post_id}"


# ─── Competitor Intelligence ─────────────────────────────────────────────────


class Competitor(models.Model):
    """A competitor tracked by the user."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, related_name="competitors"
    )
    name = models.CharField(max_length=255, help_text="Competitor brand/business name")
    website = models.URLField(blank=True)
    industry = models.CharField(max_length=100, blank=True)
    notes = models.TextField(blank=True, help_text="What they do, why you're tracking them")

    # Social handles — one field per platform, blank if not tracked
    twitter_handle = models.CharField(max_length=100, blank=True)
    instagram_handle = models.CharField(max_length=100, blank=True)
    facebook_handle = models.CharField(max_length=255, blank=True)
    linkedin_handle = models.CharField(max_length=255, blank=True)
    tiktok_handle = models.CharField(max_length=100, blank=True)
    youtube_handle = models.CharField(max_length=100, blank=True)
    threads_handle = models.CharField(max_length=100, blank=True)

    # AI-generated intelligence
    strengths = models.JSONField(
        default=list, blank=True,
        help_text="AI-identified content strengths",
    )
    weaknesses = models.JSONField(
        default=list, blank=True,
        help_text="AI-identified content gaps/weaknesses",
    )
    content_patterns = models.JSONField(
        default=dict, blank=True,
        help_text="Detected content patterns: formats, themes, frequency, tone",
    )
    threat_level = models.CharField(
        max_length=20, blank=True,
        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
        help_text="How much of a competitive threat",
    )

    last_analyzed_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]
        unique_together = ["user", "name"]

    def __str__(self):
        return f"{self.name} (tracked by {self.user})"

    @property
    def handles(self):
        """Return dict of non-empty social handles."""
        result = {}
        for platform in ["twitter", "instagram", "facebook", "linkedin", "tiktok", "youtube", "threads"]:
            handle = getattr(self, f"{platform}_handle", "")
            if handle:
                result[platform] = handle
        return result

    @property
    def platforms_tracked(self):
        """Return list of platform names with handles."""
        return list(self.handles.keys())

    @property
    def handle_count(self):
        return len(self.handles)


class CompetitorAnalysis(models.Model):
    """
    Periodic AI analysis of a competitor's social media strategy.
    Generated by the Research Agent, stored for historical comparison.
    """

    class AnalysisType(models.TextChoices):
        FULL = "full", "Full Analysis"
        QUICK = "quick", "Quick Check"
        COMPARISON = "comparison", "Head-to-Head Comparison"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    competitor = models.ForeignKey(
        Competitor, on_delete=models.SET_NULL, null=True, related_name="analyses"
    )
    user = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, related_name="competitor_analyses"
    )
    analysis_type = models.CharField(
        max_length=20, choices=AnalysisType.choices, default=AnalysisType.FULL
    )

    # AI analysis results
    summary = models.TextField(
        help_text="Executive summary of what this competitor is doing",
    )
    content_strategy = models.JSONField(
        default=dict,
        help_text="Detected strategy: themes, formats, frequency, tone, best-performing",
    )
    strengths = models.JSONField(default=list, help_text="What they do well")
    weaknesses = models.JSONField(default=list, help_text="Where they fall short")
    opportunities = models.JSONField(
        default=list,
        help_text="Gaps you can exploit — things they miss that you could do",
    )
    threats = models.JSONField(
        default=list,
        help_text="Things they do that threaten your positioning",
    )
    comparison_to_user = models.JSONField(
        default=dict,
        help_text="Head-to-head: where you're winning vs losing",
    )
    actionable_insights = models.JSONField(
        default=list,
        help_text="Specific content ideas inspired by this competitor's gaps",
    )

    tokens_used = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "Competitor analyses"

    def __str__(self):
        return f"{self.analysis_type} analysis of {self.competitor.name} ({self.created_at:%Y-%m-%d})"


class CompetitorInsight(models.Model):
    """
    Specific, actionable insight derived from competitor analysis.
    These are surfaced in the Daily Brief and Strategist recommendations.
    """

    class InsightType(models.TextChoices):
        CONTENT_GAP = "content_gap", "Content Gap"
        TREND_AHEAD = "trend_ahead", "They're Ahead on a Trend"
        WEAKNESS = "weakness", "Exploitable Weakness"
        STRATEGY_SHIFT = "strategy_shift", "Strategy Shift Detected"
        VIRAL_CONTENT = "viral_content", "Viral Content Alert"
        OPPORTUNITY = "opportunity", "Opportunity"

    class Priority(models.TextChoices):
        HIGH = "high", "High — Act Now"
        MEDIUM = "medium", "Medium — This Week"
        LOW = "low", "Low — Good to Know"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="competitor_insights"
    )
    competitor = models.ForeignKey(
        Competitor, on_delete=models.CASCADE, related_name="insights"
    )
    analysis = models.ForeignKey(
        CompetitorAnalysis, on_delete=models.CASCADE,
        related_name="insights", null=True, blank=True,
    )

    insight_type = models.CharField(max_length=30, choices=InsightType.choices)
    priority = models.CharField(max_length=10, choices=Priority.choices, default=Priority.MEDIUM)
    title = models.CharField(max_length=255)
    description = models.TextField()
    suggested_action = models.TextField(
        blank=True,
        help_text="What the user should do about this",
    )
    suggested_content_idea = models.TextField(
        blank=True,
        help_text="A specific content seed idea inspired by this insight",
    )
    is_acted_on = models.BooleanField(default=False)
    is_dismissed = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "is_acted_on", "-created_at"]),
            models.Index(fields=["user", "priority", "-created_at"]),
        ]

    def __str__(self):
        return f"[{self.insight_type}] {self.title}"


# ─── Revenue Attribution ─────────────────────────────────────────────────────


class Conversion(models.Model):
    """Tracks revenue/conversion events attributed to social posts via UTM parameters."""

    class ConversionType(models.TextChoices):
        CLICK = "click", "Link Click"
        LEAD = "lead", "Lead / Sign-up"
        SALE = "sale", "Sale"
        CUSTOM = "custom", "Custom Event"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="conversions"
    )
    post = models.ForeignKey(
        "content.Post", on_delete=models.SET_NULL,
        null=True, blank=True, related_name="conversions",
    )
    social_account = models.ForeignKey(
        "platforms.SocialAccount", on_delete=models.SET_NULL,
        null=True, blank=True, related_name="conversions",
    )
    product = models.ForeignKey(
        "products.Product", on_delete=models.SET_NULL,
        null=True, blank=True, related_name="conversions",
        help_text="Product associated with this conversion (from Sprint 6H catalog).",
    )

    conversion_type = models.CharField(
        max_length=20, choices=ConversionType.choices, default=ConversionType.CLICK,
    )
    revenue = models.DecimalField(
        max_digits=10, decimal_places=2, default=0,
        help_text="Revenue attributed to this conversion (0 if non-revenue event).",
    )
    event_name = models.CharField(max_length=255, blank=True, help_text="Custom event label")

    # UTM tracking
    utm_source = models.CharField(max_length=255, blank=True)
    utm_medium = models.CharField(max_length=255, blank=True)
    utm_campaign = models.CharField(max_length=255, blank=True)
    utm_content = models.CharField(max_length=255, blank=True, help_text="Usually the post ID")

    # Optional metadata
    metadata = models.JSONField(default=dict, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "-created_at"]),
            models.Index(fields=["utm_campaign", "-created_at"]),
            models.Index(fields=["user", "conversion_type", "-created_at"]),
        ]

    def __str__(self):
        amt = f" ${self.revenue}" if self.revenue else ""
        return f"{self.get_conversion_type_display()}{amt} — {self.post_id or 'unattributed'}"


# ─── Integration Stores ──────────────────────────────────────────────────────


class ShopifyStore(models.Model):
    """A user's connected Shopify store for revenue attribution."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="shopify_stores",
    )
    shop_domain = models.CharField(
        max_length=255, help_text="myshop.myshopify.com",
    )
    access_token = models.CharField(max_length=255)
    webhook_secret = models.CharField(
        max_length=255, blank=True,
        help_text="HMAC secret for verifying Shopify webhook signatures.",
    )
    is_active = models.BooleanField(default=True)
    orders_tracked = models.PositiveIntegerField(default=0)
    total_revenue = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    last_order_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "shop_domain")
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.shop_domain} ({self.user})"


# ─── Multi-Touch Attribution ─────────────────────────────────────────────────


class ConversionJourney(models.Model):
    """
    Tracks the full customer journey from first touch to final conversion.
    Groups multiple touchpoints into a single journey leading to one conversion.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="conversion_journeys",
    )
    conversion = models.OneToOneField(
        Conversion, on_delete=models.CASCADE, related_name="journey",
        null=True, blank=True,
    )

    # Visitor identity (cookie-based or email-based)
    visitor_id = models.CharField(
        max_length=255, db_index=True,
        help_text="Anonymous visitor ID (cookie) or email for identified users.",
    )

    # Journey outcome
    is_converted = models.BooleanField(default=False)
    total_revenue = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    touchpoint_count = models.PositiveIntegerField(default=0)

    # Timestamps
    first_touch_at = models.DateTimeField(null=True, blank=True)
    last_touch_at = models.DateTimeField(null=True, blank=True)
    converted_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "visitor_id"]),
            models.Index(fields=["user", "is_converted", "-created_at"]),
        ]

    def __str__(self):
        status = "Converted" if self.is_converted else "In progress"
        return f"{self.visitor_id} — {status} ({self.touchpoint_count} touches)"

    @property
    def attributed_revenue(self):
        """Revenue with weighted attribution across touchpoints."""
        if not self.is_converted or not self.total_revenue:
            return {}
        touches = list(self.touchpoints.order_by("touched_at"))
        if not touches:
            return {}
        count = len(touches)
        weights = {}
        if count == 1:
            weights[touches[0].pk] = 1.0
        elif count == 2:
            weights[touches[0].pk] = 0.4
            weights[touches[1].pk] = 0.6
        else:
            # 40% first, 40% last, 20% split among assists
            weights[touches[0].pk] = 0.4
            weights[touches[-1].pk] = 0.4
            assist_weight = 0.2 / (count - 2)
            for t in touches[1:-1]:
                weights[t.pk] = assist_weight
        return {
            pk: float(self.total_revenue) * w
            for pk, w in weights.items()
        }


class ConversionTouchpoint(models.Model):
    """A single touchpoint in a customer's conversion journey."""

    class TouchType(models.TextChoices):
        POST_CLICK = "post_click", "Clicked Post Link"
        PAGE_VIEW = "page_view", "Kova Page View"
        LINK_CLICK = "link_click", "Kova Link Click"
        FORM_SUBMIT = "form_submit", "Form Submission"
        AD_CLICK = "ad_click", "Ad Click"
        DIRECT = "direct", "Direct Visit"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    journey = models.ForeignKey(
        ConversionJourney, on_delete=models.CASCADE, related_name="touchpoints",
    )
    post = models.ForeignKey(
        "content.Post", on_delete=models.SET_NULL,
        null=True, blank=True, related_name="touchpoints",
    )
    touch_type = models.CharField(max_length=20, choices=TouchType.choices)

    # UTM data at time of touch
    utm_source = models.CharField(max_length=255, blank=True)
    utm_medium = models.CharField(max_length=255, blank=True)
    utm_campaign = models.CharField(max_length=255, blank=True)
    utm_content = models.CharField(max_length=255, blank=True)

    # Context
    referrer = models.URLField(blank=True)
    landing_page = models.URLField(blank=True)
    device_type = models.CharField(max_length=10, blank=True)

    touched_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["touched_at"]
        indexes = [
            models.Index(fields=["journey", "touched_at"]),
        ]

    def __str__(self):
        return f"{self.get_touch_type_display()} via {self.utm_source or 'direct'}"
