# Generated by Django 5.1.15 on 2026-04-17 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurtureSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('all_new', 'All new leads'), ('from_form', 'From form submissions'), ('from_social', 'From social (DMs & comments)'), ('high_priority', 'High-priority leads only'), ('from_platform', 'From specific platform'), ('manual', 'Manual enrollment only')], default='all_new', max_length=20)),
                ('trigger_platform', models.CharField(blank=True, help_text='Platform filter when trigger=from_platform', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurture_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('next_step_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leads.lead')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leads.nurturesequence')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['completed', 'paused', 'next_step_at'], name='leads_leade_complet_412654_idx')],
                'unique_together': {('lead', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='NurtureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('delay_hours', models.PositiveIntegerField(default=1, help_text='Hours after previous step (or enrollment)')),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('add_tag', 'Add Tag'), ('change_status', 'Change Status')], default='send_email', max_length=20)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(blank=True)),
                ('tag_value', models.CharField(blank=True, max_length=50)),
                ('status_value', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leads.nurturesequence')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
    ]
