# Generated by Django 5.1.15 on 2026-05-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_lead_temperature'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_user_id_5e62e3_idx',
            old_name='leads_lead_user_temp_idx',
        ),
    ]
