# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_reach_nurture_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source_type',
            field=models.CharField(choices=[('form_submission', 'Form Submission'), ('social_dm', 'Social DM'), ('social_comment', 'Social Comment'), ('manual', 'Manual Entry'), ('import', 'CSV / Import'), ('api', 'API'), ('commerce_purchase', 'Commerce Purchase'), ('booking', 'Booking'), ('qr_scan', 'QR Scan'), ('walk_in', 'Walk-in')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('social_interaction', 'Social Interaction'), ('note_added', 'Note Added'), ('status_changed', 'Status Changed'), ('phone_called', 'Phone Called'), ('whatsapp_sent', 'WhatsApp Sent'), ('tag_added', 'Tag Added'), ('commerce_purchase', 'Commerce Purchase'), ('booking_made', 'Booking Made'), ('booking_completed', 'Booking Completed'), ('qr_scanned', 'QR Scanned'), ('walk_in', 'Walk-in Visit')], max_length=30),
        ),
    ]
