# Generated by Django 4.2.23 on 2026-08-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_legacy_campaign_app'),
        ('leads', '0007_nurture_booking_intent_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign that generated this lead (direct attribution).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='content.marketingcampaign'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'marketing_campaign', '-first_seen_at'], name='leads_lead_user_id_bd29c1_idx'),
        ),
    ]
