# Generated by Django 5.1.15 on 2026-05-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0018_alter_post_first_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('recurrence', models.CharField(choices=[('once', 'One-time'), ('yearly', 'Annually on this date'), ('monthly', 'Monthly')], default='yearly', max_length=20)),
                ('tone_hint', models.CharField(blank=True, choices=[('warm', 'Warm / heartfelt'), ('celebratory', 'Celebratory / festive'), ('respectful', 'Respectful / reverent'), ('playful', 'Playful / fun'), ('urgent', 'Urgent / commercial'), ('informative', 'Informative / educational'), ('', 'Unspecified')], default='celebratory', max_length=50)),
                ('angles', models.JSONField(blank=True, default=list)),
                ('suggested_post_count', models.PositiveIntegerField(default=1)),
                ('lead_time_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_draft_posts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('date_type', models.CharField(choices=[('fixed', 'Fixed (same date every year)'), ('nth_weekday', 'Nth weekday of a month'), ('computed_easter', 'Computed from Easter'), ('lunar_islamic', 'Hijri lunar calendar'), ('lunar_chinese', 'Chinese lunar calendar'), ('custom_function', 'Custom date function')], max_length=20)),
                ('date_config', models.JSONField(default=dict, help_text="Date computation config. Examples:\n  fixed: {'month': 12, 'day': 25}\n  nth_weekday: {'month': 5, 'weekday': 6, 'n': 2}  (2nd Sunday May)\n  computed_easter: {'offset_days': -2}  (Good Friday)\n  lunar_islamic: {'hijri_month': 10, 'hijri_day': 1}  (Eid al-Fitr)\n  custom_function: {'function_name': 'friday_after_thanksgiving'}")),
                ('countries', models.JSONField(blank=True, default=list, help_text="ISO-3166-1 alpha-2 codes. ['RW', 'KE'] for East Africa, [] for global.")),
                ('excluded_countries', models.JSONField(blank=True, default=list, help_text='Countries to exclude from a global holiday (rare).')),
                ('category', models.CharField(choices=[('national_holiday', 'National / statutory holiday'), ('religious', 'Religious observance'), ('commercial', 'Commercial / shopping holiday'), ('cultural', 'Cultural moment'), ('awareness_day', 'Awareness day'), ('industry_specific', 'Industry-specific moment'), ('personal', 'Personal / business event')], max_length=30)),
                ('religion', models.CharField(blank=True, choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('hindu', 'Hindu'), ('buddhist', 'Buddhist'), ('jewish', 'Jewish'), ('secular', 'Secular'), ('', 'None / not applicable')], default='', max_length=30)),
                ('industries', models.JSONField(blank=True, default=list, help_text='Industry slugs the holiday is most relevant to. Empty = all industries.')),
                ('sensitivity_level', models.CharField(choices=[('safe', 'Safe — broad audience, low risk'), ('consider', 'Consider — depends on market context'), ('high', 'High — politically/religiously charged, requires opt-in')], default='safe', max_length=20)),
                ('requires_opt_in', models.BooleanField(default=False)),
                ('default_relevance_score', models.IntegerField(default=50, help_text='Base relevance 0-100. Multiplied by industry/country/preference factors.')),
                ('suggested_post_count', models.PositiveIntegerField(default=2)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='How many days before the date drafts should be generated.')),
                ('tone_hint', models.CharField(blank=True, choices=[('warm', 'Warm / heartfelt'), ('celebratory', 'Celebratory / festive'), ('respectful', 'Respectful / reverent'), ('playful', 'Playful / fun'), ('urgent', 'Urgent / commercial'), ('informative', 'Informative / educational'), ('', 'Unspecified')], default='', max_length=50)),
                ('angles', models.JSONField(blank=True, default=list, help_text='Suggested content angles. List of short strings.')),
                ('avoid_phrases', models.JSONField(blank=True, default=list, help_text='Phrases the generator must avoid (anti-generic guardrail).')),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, help_text="Origin of this entry: 'python-holidays', 'curated', 'admin', etc.", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='calendar_in_categor_5ae2fb_idx'), models.Index(fields=['religion'], name='calendar_in_religio_49711e_idx'), models.Index(fields=['is_active'], name='calendar_in_is_acti_e33a70_idx')],
            },
        ),
        migrations.CreateModel(
            name='HolidayOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, help_text="Caveats specific to this occurrence (e.g., 'date may shift ±1 by region').", max_length=200)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendar_intel.holiday')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HolidayDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('relevance_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued for generation'), ('generating', 'Generating'), ('drafts_ready', 'Drafts ready for review'), ('approved', 'Approved'), ('dismissed', 'Dismissed by user'), ('failed', 'Generation failed'), ('expired', 'Date passed without action')], default='queued', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='calendar_intel.customevent')),
                ('posts_generated', models.ManyToManyField(blank=True, related_name='holiday_drafts', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_drafts', to=settings.AUTH_USER_MODEL)),
                ('holiday_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='calendar_intel.holidayoccurrence')),
            ],
            options={
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='UserHolidayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('custom_relevance_score', models.IntegerField(blank=True, null=True)),
                ('custom_lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_post_count', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_draft_posts', models.BooleanField(default=True)),
                ('muted_until', models.DateField(blank=True, help_text="If set, holiday is muted until this date. Used for 'mute this year only'.", null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_intel.holiday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customevent',
            index=models.Index(fields=['user', 'is_active'], name='calendar_in_user_id_a4f05d_idx'),
        ),
        migrations.AddIndex(
            model_name='customevent',
            index=models.Index(fields=['date'], name='calendar_in_date_f9f537_idx'),
        ),
        migrations.AddIndex(
            model_name='holidayoccurrence',
            index=models.Index(fields=['date'], name='calendar_in_date_d71f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='holidayoccurrence',
            index=models.Index(fields=['year', 'date'], name='calendar_in_year_6bd34b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidayoccurrence',
            unique_together={('holiday', 'year')},
        ),
        migrations.AddIndex(
            model_name='holidaydraft',
            index=models.Index(fields=['user', 'target_date'], name='calendar_in_user_id_51f81d_idx'),
        ),
        migrations.AddIndex(
            model_name='holidaydraft',
            index=models.Index(fields=['status'], name='calendar_in_status_ed840f_idx'),
        ),
        migrations.AddConstraint(
            model_name='holidaydraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_event__isnull', True), ('holiday_occurrence__isnull', False)), models.Q(('custom_event__isnull', False), ('holiday_occurrence__isnull', True)), _connector='OR'), name='holidaydraft_exactly_one_moment'),
        ),
        migrations.AlterUniqueTogether(
            name='userholidaypreference',
            unique_together={('user', 'holiday')},
        ),
    ]
