# Generated by Django 5.1.15 on 2026-04-10 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['position', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order'), ('unlimited', 'Unlimited / Digital')], default='in_stock', max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text="Leave blank if you don't track exact numbers", null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Flag as low stock below this number')),
                ('is_featured', models.BooleanField(default=False, help_text='Push harder in content')),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='E.g. ["bestseller", "new arrival"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock Warning'), ('out_of_stock', 'Out of Stock'), ('restocked', 'Restocked'), ('featured_no_content', 'Featured — No Recent Content'), ('overstock_no_promo', 'In Stock — Not Being Promoted')], max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order'), ('unlimited', 'Unlimited / Digital')], max_length=20)),
                ('new_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order'), ('unlimited', 'Unlimited / Digital')], max_length=20)),
                ('previous_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('new_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('manual', 'Manual Update'), ('sale', 'Sale'), ('restock', 'Restock'), ('adjustment', 'Adjustment')], default='manual', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_updates', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'stock_status'], name='products_pr_user_id_5d184b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_featured'], name='products_pr_user_id_537157_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_active'], name='products_pr_user_id_cefa3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'name')},
        ),
    ]
