# Generated by Django 5.1.15 on 2026-04-15 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offering_type',
            field=models.CharField(choices=[('product', 'Physical Product'), ('service', 'Service'), ('digital', 'Digital Product')], default='product', help_text='Product, service, or digital — determines how AI talks about it', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'offering_type'], name='products_pr_user_id_737c7f_idx'),
        ),
    ]
