# Generated by Django 5.1.15 on 2026-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_offering_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='URLs of extra product images for carousel content, e.g. ["/media/product_images/side.jpg", "https://cdn.example.com/img.jpg"]'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, help_text='SKU or external platform product ID — for syncing with Shopify, WooCommerce, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, help_text="Direct purchase/product page URL — used for 'Shop Now' CTAs in generated content."),
        ),
    ]
