# Generated by Django 5.1.15 on 2026-06-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_businessasset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businessasset',
            new_name='products_bu_user_id_be6075_idx',
            old_name='products_ba_user_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='businessasset',
            new_name='products_bu_user_id_fcd021_idx',
            old_name='products_ba_user_st_idx',
        ),
    ]
