# Generated by Django 5.1.6 on 2026-07-02 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_legacy_campaign_app'),
        ('products', '0019_rename_products_ba_user_ty_idx_products_bu_user_id_be6075_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visual_mode',
            field=models.CharField(choices=[('as_is', 'Use as-is'), ('enhance_lighting', 'Enhance lighting only'), ('quick_polish', 'Quick polish'), ('pro_scene', 'Studio polish')], default='pro_scene', help_text='How Kova treats product photos before content generation.', max_length=20),
        ),
        migrations.CreateModel(
            name='RevenueFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('landing_url', models.CharField(blank=True, max_length=500)),
                ('stages', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('archived', 'Archived')], default='active', max_length=12)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='products.product')),
                ('source_post', models.ForeignKey(blank=True, help_text='The content that kicked off this funnel, when known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_funnels', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_funnels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status', '-updated_at'], name='products_re_user_id_269c8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_funnel_per_product')],
            },
        ),
    ]
