# Generated by Django 4.2.23 on 2026-09-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_visual_mode_revenuefunnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='booking_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketplace_partner',
        ),
    ]
