# Generated by Django 5.1.15 on 2026-03-27 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('comment', 'Comment'), ('reply', 'Reply'), ('mention', 'Mention'), ('dm', 'Direct Message')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('ai_replied', 'AI Replied'), ('user_replied', 'User Replied'), ('ignored', 'Ignored'), ('flagged', 'Flagged')], default='new', max_length=20)),
                ('author_name', models.CharField(max_length=255)),
                ('author_username', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('ai_suggested_reply', models.TextField(blank=True)),
                ('ai_reply_sent', models.TextField(blank=True)),
                ('platform_interaction_id', models.CharField(blank=True, max_length=255)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='content.post')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
