# Generated by Django 5.1.15 on 2026-03-31 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Superfan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_username', models.CharField(db_index=True, max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('platforms', models.JSONField(blank=True, default=list, help_text='Platforms this person engages on')),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('rising', 'Rising'), ('loyal', 'Loyal'), ('superfan', 'Superfan')], default='rising', max_length=20)),
                ('last_sentiment', models.CharField(blank=True, max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="AI-generated notes about this person's engagement patterns.")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superfans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-interaction_count'],
                'unique_together': {('user', 'author_username')},
            },
        ),
    ]
