# Generated by Django 5.1.15 on 2026-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0002_add_superfan_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='platform_interaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='sentiment',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ai_replied', 'AI Replied'), ('user_replied', 'User Replied'), ('ignored', 'Ignored'), ('flagged', 'Flagged')], db_index=True, default='new', max_length=20),
        ),
    ]
