# Generated by Django 5.1.15 on 2026-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_mpesa_phone_userprofile_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brand_restrictions',
            field=models.TextField(blank=True, help_text="Topics, words, or themes to avoid. E.g., 'Never mention competitors by name.'"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='content_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('sw_en', 'Swahili & English mix'), ('fr', 'French'), ('fr_en', 'French & English mix'), ('yo', 'Yoruba'), ('yo_en', 'Yoruba & English mix'), ('zu', 'Zulu'), ('sheng', 'Sheng'), ('pidgin', 'Pidgin English'), ('other', 'Other')], default='en', help_text='Primary language for generated content.', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_offerings',
            field=models.JSONField(blank=True, default=list, help_text="Main products or services. E.g., ['Custom cakes', 'Catering', 'Baking classes']"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform_priority',
            field=models.JSONField(blank=True, default=dict, help_text="Platform importance ranking. E.g., {'linkedin': 1, 'twitter': 2, 'instagram': 3}"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tone_attributes',
            field=models.JSONField(blank=True, default=list, help_text="Structured tone descriptors. E.g., ['confident', 'witty', 'educational']"),
        ),
    ]
