# Generated by Django 5.1.15 on 2026-04-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_cta_email_userprofile_cta_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_pause',
            field=models.BooleanField(default=False, help_text='If True, ALL autonomous agent actions are halted immediately. No publishing, no seeds, no replies, no media queue processing.'),
        ),
    ]
