# Generated by Django 5.1.15 on 2026-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_onboarding_intelligence_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Primary city — used for localized content references.', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', help_text="ISO 3166-1 alpha-2 country code (e.g., 'RW', 'KE', 'US'). Drives which holidays surface for this user.", max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_markets',
            field=models.JSONField(blank=True, default=list, help_text="Additional ISO 3166-1 alpha-2 codes the business serves. E.g., ['UG', 'TZ']. Phase 4 multi-market feature."),
        ),
    ]
