# Generated by Django 5.1.15 on 2026-05-15 17:47
# Hand-edited: added a data migration that remaps the deprecated
# `auto_engage` boolean onto the new `engage_autonomy_level` enum per
# docs/specs/ENGAGE_AGENT_V2_SPEC.md. auto_engage=True maps to SUGGEST
# (NOT graduated — explicit opt-in required for actual autonomy) and
# auto_engage=False maps to OFF.

from django.db import migrations, models


def remap_auto_engage_to_autonomy_level(apps, schema_editor):
    """Map deprecated auto_engage boolean onto engage_autonomy_level.

    auto_engage=True  -> SUGGEST   (user had AI-reply queuing enabled;
                                     give them the same behaviour by
                                     default. They must explicitly opt up
                                     to GRADUATED to get auto-send.)
    auto_engage=False -> OFF       (user had AI replies disabled)
    """
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(auto_engage=True).update(
        engage_autonomy_level="suggest",
    )
    UserProfile.objects.filter(auto_engage=False).update(
        engage_autonomy_level="off",
    )


def reverse_remap_noop(apps, schema_editor):
    """Reverse migration is a no-op — the original auto_engage value is
    preserved on the column; we only set the new field."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_industry_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='engage_autonomy_level',
            field=models.CharField(choices=[('off', 'Off — no AI replies'), ('suggest', 'Suggest — AI drafts, I approve every one'), ('graduated', 'Graduated — auto-send safe replies, queue tricky ones'), ('aggressive', 'Aggressive — auto-send aggressively (Agency only)')], default='suggest', help_text='How much social media autonomy to give the Engage Agent. OFF disables AI replies entirely. SUGGEST queues every AI reply for review. GRADUATED auto-sends at confidence ≥ 0.85 and queues 0.50-0.85 as drafts. AGGRESSIVE auto-sends at ≥ 0.70. Plan-tier-gated — see docs/specs/ENGAGE_AGENT_V2_SPEC.md.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auto_engage',
            field=models.BooleanField(default=False, help_text="DEPRECATED — use engage_autonomy_level instead. Kept for two release cycles to avoid breaking admin tools / external API clients that haven't migrated yet. Phase 1 W2 (May 2026)."),
        ),
        migrations.RunPython(
            remap_auto_engage_to_autonomy_level,
            reverse_remap_noop,
        ),
    ]
