# Generated by Django 5.1.15 on 2026-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_engage_autonomy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adapt_last_run_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent Adapt v2 cycle for this user.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adapt_paused',
            field=models.BooleanField(default=False, help_text='If True, Adapt Agent v2 skips this user. Manual override for users who want to lock their settings in place.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dna_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Promoted / retired Content DNA patterns from the Adapt loop. Shape: {"promoted": [{"combo": {...}, "boost": 1.5, ...}, ...], "retired": [{"combo": {...}, "set_at": "..."}, ...]}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='optimal_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Per-platform optimal posting hours/days from Adapt v1\'s scheduling optimiser. Shape: {"instagram": {"best_hours": [9, 18], "best_days": ["mon", "tue"]}, ...}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pillar_weights',
            field=models.JSONField(blank=True, default=dict, help_text='Per-pillar rotation weights (0.2-2.0, default 1.0). Adapt Agent v2 mutates these based on per-pillar engagement. The Strategist + Create agents pull from pillars proportionally.'),
        ),
    ]
