# Generated by Django 5.1.15 on 2026-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_pilotmetricssnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_support_staff',
            field=models.BooleanField(default=False, help_text='Limited staff role: read-only admin dashboard. Requires is_staff=True. Superusers bypass write restrictions.'),
        ),
    ]
