# Generated by Django 4.2.23 on 2026-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_userprofile_business_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('kova', 'Kova'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('agency', 'Agency')], default='starter', max_length=20),
        ),
    ]
