# Generated by Django 5.1.15 on 2026-03-27 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('research', 'Research Agent'), ('create', 'Content Creator Agent'), ('adapt', 'Platform Adapter Agent'), ('engage', 'Engagement Agent'), ('analyst', 'Analytics Agent'), ('strategist', 'Chief Strategist')], max_length=20)),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_approval', 'Needs Approval')], default='started', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('research', 'Research Agent'), ('create', 'Content Creator Agent'), ('adapt', 'Platform Adapter Agent'), ('engage', 'Engagement Agent'), ('analyst', 'Analytics Agent'), ('strategist', 'Chief Strategist')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions for this agent.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Agent-specific configuration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agent_type'],
                'unique_together': {('user', 'agent_type')},
            },
        ),
    ]
