# Generated by Django 5.1.15 on 2026-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentaction_input_tokens_agentaction_model_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaction',
            name='agent_type',
            field=models.CharField(choices=[('research', 'Research Agent'), ('create', 'Content Creator Agent'), ('adapt', 'Platform Adapter Agent'), ('engage', 'Engagement Agent'), ('analyst', 'Analytics Agent'), ('strategist', 'Chief Strategist')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agentaction',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_approval', 'Needs Approval')], db_index=True, default='started', max_length=20),
        ),
    ]
