# Generated by Django 5.1.15 on 2026-04-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentaction_outcome_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['user', 'agent_type', '-created_at'], name='agents_agen_user_id_50dfba_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['user', 'status', '-created_at'], name='agents_agen_user_id_fc5bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['agent_type', 'status', '-created_at'], name='agents_agen_agent_t_f09204_idx'),
        ),
    ]
