# Generated by Django 5.1.15 on 2026-04-06 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentaction_agents_agen_user_id_50dfba_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic')], default='openrouter', help_text='Primary LLM provider.', max_length=20)),
                ('default_model', models.CharField(default='qwen/qwen3.6-plus:free', help_text='Default model when no task-specific model is set.', max_length=120)),
                ('paid_fallback_model', models.CharField(blank=True, default='gpt-4o-mini', help_text='Paid model to auto-escalate to when free models fail. Leave blank to disable.', max_length=120)),
                ('paid_fallback_provider', models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic')], default='openai', help_text='Provider for the paid fallback model.', max_length=20)),
                ('model_premium', models.CharField(default='qwen/qwen3.6-plus:free', help_text='Premium tier — creative generation and user-facing text.', max_length=120)),
                ('model_workhorse', models.CharField(default='qwen/qwen3.6-plus:free', help_text='Workhorse tier — reasoning, research, strategy.', max_length=120)),
                ('model_fast', models.CharField(default='stepfun/step-3.5-flash:free', help_text='Fast tier — classification, DNA extraction, scoring.', max_length=120)),
                ('task_model_overrides', models.JSONField(blank=True, default=dict, help_text='Per-task model overrides. Keys like "create.generate", "engage.reply", etc.')),
                ('free_fallback_models', models.JSONField(blank=True, default=list, help_text='Ordered list of free model identifiers to try when the primary fails.')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, help_text='Max model attempts before giving up (including fallbacks).')),
                ('paid_fallback_enabled', models.BooleanField(default=True, help_text='Whether to auto-escalate to paid model when free models fail.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configuration',
            },
        ),
    ]
