# Generated by Django 5.1.15 on 2026-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_llm_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='plan_model_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-plan tier overrides. {"starter": {"premium": "model", "workhorse": "model", "fast": "model"}, ...}'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='plan_rate_limits',
            field=models.JSONField(blank=True, default=dict, help_text='Per-plan rate limits. {"starter": {"max_calls_per_hour": 30, "max_tokens_per_day": 100000}, ...}'),
        ),
    ]
