# Generated by Django 5.1.15 on 2026-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_update_llmconfig_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='default_model',
            field=models.CharField(default='deepseek/deepseek-v3.2', help_text='Default model when no task-specific model is set.', max_length=120),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model_fast',
            field=models.CharField(default='deepseek/deepseek-v3.2', help_text='Fast tier — classification, DNA extraction, scoring.', max_length=120),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model_premium',
            field=models.CharField(default='deepseek/deepseek-v3.2', help_text='Premium tier — creative generation and user-facing text.', max_length=120),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model_workhorse',
            field=models.CharField(default='deepseek/deepseek-v3.2', help_text='Workhorse tier — reasoning, research, strategy.', max_length=120),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='paid_fallback_model',
            field=models.CharField(blank=True, default='google/gemini-2.0-flash-001', help_text='Paid model to auto-escalate to when free models fail. Leave blank to disable.', max_length=120),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='paid_fallback_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic')], default='openrouter', help_text='Provider for the paid fallback model.', max_length=20),
        ),
    ]
