# Generated by Django 5.1.15 on 2026-04-06 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0011_add_media_prompt'),
        ('platforms', '0006_socialaccount_platforms_s_user_id_479427_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Optional label, e.g. 'Product Photos'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rhythm_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('time_slots', models.JSONField(default=list, help_text='Daily: ["09:00","13:00"] | Weekly: [{"day":0,"time":"09:00"}]')),
                ('active_days', models.JSONField(default=list, help_text='Active days (0=Mon..6=Sun). Empty list means every day.')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('notify_when_low', models.PositiveIntegerField(default=3, help_text='Alert user when queue drops to N items or fewer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_queues', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Queue',
                'verbose_name_plural': 'Media Queues',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'social_account')},
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='queue_media/%Y/%m/')),
                ('image_cropped', models.ImageField(blank=True, help_text='Auto-cropped version optimised for the target platform.', upload_to='queue_media/%Y/%m/cropped/')),
                ('caption', models.TextField(blank=True, help_text='Optional caption for this post.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='Calculated publish time based on queue rhythm.', null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, help_text='Post created when this item is published (for analytics).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_source', to='content.post')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media_queue.mediaqueue')),
            ],
            options={
                'verbose_name': 'Queue Item',
                'verbose_name_plural': 'Queue Items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['queue', 'status', 'scheduled_for'], name='media_queue_queue_i_36ff4f_idx')],
            },
        ),
    ]
