# Generated by Django 5.1.15 on 2026-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaqueue',
            name='posts_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='How many photos to post per time slot (1 = single, 2+ = bulk).'),
        ),
    ]
