"""
AI Campaign Builder — Generate a full campaign from a single prompt.

Creates a Campaign + multiple ContentSeeds across platforms,
scheduled over the campaign duration. The Create Agent then
processes each seed into platform-optimized posts.
"""

import json
import logging
from datetime import timedelta

from celery import shared_task
from django.utils import timezone

logger = logging.getLogger(__name__)


def build_campaign_from_prompt(
    user,
    prompt,
    duration_days=7,
    *,
    voice_brief=None,
    include_email=False,
    include_status=False,
    auto_generate=True,
):
    """
    Shared campaign builder used by AI prompt and Voice-to-Campaign flows.

    Returns dict with campaign_id, name, seeds_created, email_campaign_id (optional).
    """
    from apps.campaigns.models import Campaign, CampaignEmail, CampaignNote, CampaignSeed
    from apps.content.models import ContentSeed
    from apps.platforms.models import SocialAccount

    platforms = list(
        SocialAccount.objects.filter(user=user, is_active=True)
        .values_list("platform", flat=True)
    )
    if not platforms:
        return {"error": "No connected platforms"}

    profile = getattr(user, "profile", None)
    business_name = getattr(profile, "company_name", "") if profile else ""
    brand_voice = getattr(profile, "brand_voice", "") if profile else ""

    plan = _generate_campaign_plan(
        user, prompt, platforms, business_name, brand_voice, duration_days,
    )
    if not plan:
        return {"error": "Failed to generate campaign plan"}

    start_date = timezone.now().date()
    end_date = start_date + timedelta(days=duration_days)

    objective_map = {
        "awareness": Campaign.Objective.AWARENESS,
        "engagement": Campaign.Objective.ENGAGEMENT,
        "traffic": Campaign.Objective.TRAFFIC,
        "leads": Campaign.Objective.LEADS,
        "sales": Campaign.Objective.SALES,
        "brand": Campaign.Objective.LAUNCH,
        "launch": Campaign.Objective.LAUNCH,
    }
    objective = objective_map.get(
        plan.get("objective", "").lower(), Campaign.Objective.ENGAGEMENT,
    )

    campaign = Campaign.objects.create(
        user=user,
        name=plan.get("name", prompt[:60]),
        description=plan.get("description", prompt),
        objective=objective,
        status=Campaign.Status.ACTIVE,
        start_date=start_date,
        end_date=end_date,
        target_platforms=platforms,
        target_audience=plan.get("target_audience", ""),
    )

    CampaignNote.objects.create(
        campaign=campaign,
        user=user,
        content=f"Campaign auto-generated by AI from prompt: {prompt[:200]}",
        note_type="status_change",
    )

    seeds_created = 0
    seed_ids = []
    seed_ideas = plan.get("seeds", [])

    for i, seed_data in enumerate(seed_ideas[:10]):
        if not isinstance(seed_data, dict):
            continue

        idea = seed_data.get("idea", "")
        if not idea:
            continue

        seed_platforms = seed_data.get("platforms", platforms[:2])
        seed_platforms = [p for p in seed_platforms if p in platforms] or platforms[:1]

        seed = ContentSeed.objects.create(
            user=user,
            idea=idea,
            notes=f"[Campaign AI] Part of campaign: {campaign.name}",
            target_platforms=seed_platforms,
        )

        role = "primary" if i == 0 else ("follow_up" if i == len(seed_ideas) - 1 else "supporting")
        CampaignSeed.objects.create(
            campaign=campaign,
            seed=seed,
            role=role,
            sequence_order=i,
        )
        seed_ids.append(str(seed.pk))
        seeds_created += 1

    if voice_brief:
        voice_brief.campaign = campaign
        voice_brief.seeds_created = seeds_created
        voice_brief.save(update_fields=["campaign", "seeds_created"])

    email_campaign_id = None
    if include_email or plan.get("include_email"):
        email_campaign_id = _create_linked_email_campaign(user, campaign, plan, prompt)

    status_ids = []
    if include_status or plan.get("include_whatsapp_status"):
        status_ids = _create_status_updates_from_plan(user, campaign, plan, duration_days)

    if auto_generate and seed_ids:
        from apps.content.tasks import generate_from_seed

        for seed_id in seed_ids:
            generate_from_seed.delay(seed_id)

    logger.info(
        "Campaign builder: created '%s' with %d seeds for %s",
        campaign.name, seeds_created, user.email,
    )

    return {
        "campaign_id": str(campaign.id),
        "name": campaign.name,
        "seeds_created": seeds_created,
        "email_campaign_id": email_campaign_id,
        "status_ids": status_ids,
        "status_count": len(status_ids),
    }


def _create_linked_email_campaign(user, campaign, plan, prompt):
    """Create an AI email campaign linked to the social campaign; auto-send when ready."""
    try:
        from apps.campaigns.models import CampaignEmail
        from apps.emails.automation import ai_generate_email_content, create_email_campaign

        key_message = plan.get("key_message") or plan.get("description") or prompt[:200]
        generated = ai_generate_email_content(
            user,
            f"Campaign: {campaign.name}. Message: {key_message}",
        )
        if not generated:
            generated = {
                "subject": (plan.get("email_subject") or key_message)[:255],
                "preview_text": key_message[:255],
                "body_html": plan.get("email_html") or f"<p>{key_message}</p>",
            }

        email_camp = create_email_campaign(
            user,
            name=f"Email: {campaign.name}",
            subject=generated.get("subject", key_message)[:255],
            html_content=generated.get("body_html", f"<p>{key_message}</p>"),
            preview_text=generated.get("preview_text", key_message[:255]),
            ai_generated=True,
            auto_send=True,
        )
        CampaignEmail.objects.create(
            campaign=campaign,
            email_campaign=email_camp,
            role=CampaignEmail.Role.ANNOUNCEMENT,
        )
        return str(email_camp.pk)
    except Exception as e:
        logger.warning("Linked email campaign creation failed: %s", e)
        return None


def _create_status_updates_from_plan(user, campaign, plan, duration_days):
    """Create WhatsApp Status drafts from campaign plan status_updates."""
    from apps.whatsapp.models import StatusContent

    updates = plan.get("status_updates") or []
    if not updates:
        key_message = plan.get("key_message") or plan.get("description") or campaign.name
        updates = [
            {"text": key_message[:200], "category": "announcement", "day": 1},
            {
                "text": (plan.get("description") or key_message)[:200],
                "category": "offer" if "offer" in (plan.get("description") or "").lower() else "tip",
                "day": min(3, duration_days),
            },
        ]

    category_map = {
        "offer": StatusContent.ContentCategory.OFFER,
        "announcement": StatusContent.ContentCategory.ANNOUNCEMENT,
        "tip": StatusContent.ContentCategory.TIP,
        "testimonial": StatusContent.ContentCategory.TESTIMONIAL,
        "bts": StatusContent.ContentCategory.BTS,
        "new_product": StatusContent.ContentCategory.NEW_PRODUCT,
    }

    status_ids = []
    start = timezone.now().replace(hour=7, minute=0, second=0, microsecond=0)

    for item in updates[:5]:
        if not isinstance(item, dict):
            continue
        text = (item.get("text") or "").strip()
        if not text:
            continue
        raw_cat = (item.get("category") or "announcement").lower()
        category = category_map.get(raw_cat, StatusContent.ContentCategory.ANNOUNCEMENT)
        day_offset = max(0, int(item.get("day", 1)) - 1)
        scheduled = start + timedelta(days=min(day_offset, duration_days))

        status_obj = StatusContent.objects.create(
            user=user,
            text=text[:700],
            caption=(item.get("caption") or "")[:500],
            category=category,
            state=StatusContent.StatusState.READY,
            scheduled_for=scheduled,
            ai_generated=True,
            ai_reasoning=f"Listen & Launch campaign: {campaign.name}",
        )
        status_obj.generate_share_url()
        status_obj.save(update_fields=["share_url"])
        status_ids.append(str(status_obj.pk))

    if status_ids:
        from apps.campaigns.models import CampaignNote

        CampaignNote.objects.create(
            campaign=campaign,
            user=user,
            content=f"Created {len(status_ids)} WhatsApp Status draft(s) for Listen & Launch.",
            note_type="status_change",
        )

    return status_ids


@shared_task(name="campaigns.ai_build_campaign")
def ai_build_campaign(
    user_id,
    prompt,
    duration_days=7,
    include_email=False,
    include_status=False,
):
    """Celery entry: build a full campaign from a text prompt."""
    from django.contrib.auth import get_user_model

    User = get_user_model()
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        return {"error": "User not found"}

    return build_campaign_from_prompt(
        user, prompt, duration_days, include_email=include_email, include_status=include_status,
    )


def _generate_campaign_plan(user, prompt, platforms, business_name, brand_voice, duration_days):
    """Use LLM to generate a structured campaign plan."""
    try:
        from apps.accounts.segments import build_segment_prompt_context
        from apps.agents.llm import generate, get_model_for_task

        profile = getattr(user, "profile", None)
        platform_list = ", ".join(platforms)
        audience = (getattr(profile, "target_audience", "") or "").strip()
        offerings = getattr(profile, "key_offerings", []) or []
        goals = getattr(profile, "goals", []) or []
        segment_context = build_segment_prompt_context(
            profile=profile,
            connected_platforms=platforms,
        )
        system = (
            f"You are a marketing campaign strategist for {business_name or 'a business'}.\n"
            f"Brand voice: {brand_voice or 'professional and engaging'}.\n"
            f"Connected platforms: {platform_list}.\n"
            f"Campaign duration: {duration_days} days.\n"
            f"Target audience: {audience or 'General audience'}.\n"
            f"Key offerings: {', '.join(str(item) for item in offerings[:5]) or 'None provided'}.\n"
            f"Goals: {', '.join(str(item) for item in goals[:4]) or 'Grow awareness and engagement'}.\n"
            f"{segment_context}"
        )

        user_prompt = (
            f"Create a campaign plan for this goal:\n\n{prompt}\n\n"
            f"Use the business model context above when choosing the campaign angle, CTA, and seed ideas.\n"
            f"Match the conversion path to the business: product sellers should drive purchase intent, "
            f"service businesses should drive booking or inquiry intent, digital sellers should drive access or enrollment intent, "
            f"and expert-led brands should favor authority, audience growth, list growth, or inbound opportunity generation unless the prompt clearly asks for direct sales.\n\n"
            f"Return ONLY valid JSON with this structure:\n"
            f'{{\n'
            f'  "name": "Short campaign name (max 60 chars)",\n'
            f'  "description": "One-paragraph campaign description",\n'
            f'  "objective": "awareness|engagement|traffic|leads|sales|launch",\n'
            f'  "target_audience": "Who this campaign targets",\n'
            f'  "include_email": false,\n'
            f'  "include_whatsapp_status": false,\n'
            f'  "email_subject": "Optional email subject if include_email is true",\n'
            f'  "key_message": "Core message in one sentence",\n'
            f'  "status_updates": [\n'
            f'    {{\n'
            f'      "text": "Short WhatsApp Status text (max 200 chars, punchy)",\n'
            f'      "category": "announcement|offer|tip|new_product",\n'
            f'      "day": 1\n'
            f'    }}\n'
            f'  ],\n'
            f'  "seeds": [\n'
            f'    {{\n'
            f'      "idea": "Detailed content idea with angle and key message",\n'
            f'      "platforms": ["platform1", "platform2"],\n'
            f'      "day": 1\n'
            f'    }}\n'
            f'  ]\n'
            f'}}\n\n'
            f"Generate 4-7 content seeds spread across {duration_days} days.\n"
            f"Each seed should have a unique angle — don't repeat the same message.\n"
            f"Mix content types: educational, social proof, behind-the-scenes, CTA-focused.\n"
            f"Set include_email to true if the prompt mentions email, newsletter, or subscribers.\n"
            f"Set include_whatsapp_status to true if the prompt mentions WhatsApp Status, WA status, or status updates.\n"
            f"Generate 2-4 status_updates when include_whatsapp_status is true — short, punchy, Kenyan-friendly tone."
        )

        model = get_model_for_task("create.strategize", user=user)
        resp = generate(
            model=model, system=system, prompt=user_prompt,
            temperature=0.7, max_tokens=1500, user=user,
        )

        if resp and resp.text:
            text = resp.text.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1] if "\n" in text else text[3:]
                if text.endswith("```"):
                    text = text[:-3]
            return json.loads(text.strip())
    except Exception as e:
        logger.error("Campaign plan generation failed: %s", e)

    return None
