"""
AI Campaign Builder — Generate a full campaign from a single prompt.

Creates a Campaign + multiple ContentSeeds across platforms,
scheduled over the campaign duration. The Create Agent then
processes each seed into platform-optimized posts.
"""

import json
import logging
from datetime import timedelta

from celery import shared_task
from django.utils import timezone

logger = logging.getLogger(__name__)


@shared_task(name="campaigns.ai_build_campaign")
def ai_build_campaign(user_id, prompt, duration_days=7):
    """
    Build a full campaign from a user prompt.

    1. Uses LLM to generate campaign strategy (name, objective, seed ideas)
    2. Creates Campaign object
    3. Creates ContentSeeds linked to the campaign, spread across duration
    4. Each seed will be picked up by the Create Agent for content generation
    """
    from django.contrib.auth import get_user_model

    from apps.campaigns.models import Campaign, CampaignNote, CampaignSeed
    from apps.content.models import ContentSeed
    from apps.platforms.models import SocialAccount

    User = get_user_model()
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        return {"error": "User not found"}

    platforms = list(
        SocialAccount.objects.filter(user=user, is_active=True)
        .values_list("platform", flat=True)
    )
    if not platforms:
        return {"error": "No connected platforms"}

    profile = getattr(user, "profile", None)
    business_name = getattr(profile, "company_name", "") if profile else ""
    brand_voice = getattr(profile, "brand_voice", "") if profile else ""

    # Step 1: Generate campaign plan via LLM
    plan = _generate_campaign_plan(
        user, prompt, platforms, business_name, brand_voice, duration_days,
    )
    if not plan:
        return {"error": "Failed to generate campaign plan"}

    # Step 2: Create Campaign
    start_date = timezone.now().date()
    end_date = start_date + timedelta(days=duration_days)

    objective_map = {
        "awareness": Campaign.Objective.AWARENESS,
        "engagement": Campaign.Objective.ENGAGEMENT,
        "traffic": Campaign.Objective.TRAFFIC,
        "leads": Campaign.Objective.LEADS,
        "sales": Campaign.Objective.SALES,
        "brand": Campaign.Objective.BRAND,
    }
    objective = objective_map.get(
        plan.get("objective", "").lower(), Campaign.Objective.ENGAGEMENT,
    )

    campaign = Campaign.objects.create(
        user=user,
        name=plan.get("name", prompt[:60]),
        description=plan.get("description", prompt),
        objective=objective,
        status=Campaign.Status.DRAFT,
        start_date=start_date,
        end_date=end_date,
        target_platforms=platforms,
        target_audience=plan.get("target_audience", ""),
    )

    CampaignNote.objects.create(
        campaign=campaign,
        user=user,
        content=f"Campaign auto-generated by AI from prompt: {prompt[:200]}",
        note_type="status_change",
    )

    # Step 3: Create ContentSeeds from the plan
    seeds_created = 0
    seed_ideas = plan.get("seeds", [])

    for i, seed_data in enumerate(seed_ideas[:10]):  # Cap at 10 seeds
        if not isinstance(seed_data, dict):
            continue

        idea = seed_data.get("idea", "")
        if not idea:
            continue

        seed_platforms = seed_data.get("platforms", platforms[:2])
        # Filter to connected platforms only
        seed_platforms = [p for p in seed_platforms if p in platforms] or platforms[:1]

        seed = ContentSeed.objects.create(
            user=user,
            idea=idea,
            notes=f"[Campaign AI] Part of campaign: {campaign.name}",
            target_platforms=seed_platforms,
        )

        role = "primary" if i == 0 else ("follow_up" if i == len(seed_ideas) - 1 else "supporting")
        CampaignSeed.objects.create(
            campaign=campaign,
            seed=seed,
            role=role,
            sequence_order=i,
        )
        seeds_created += 1

    logger.info(
        "AI Campaign Builder: created campaign '%s' with %d seeds for %s",
        campaign.name, seeds_created, user.email,
    )

    return {
        "campaign_id": str(campaign.id),
        "name": campaign.name,
        "seeds_created": seeds_created,
    }


def _generate_campaign_plan(user, prompt, platforms, business_name, brand_voice, duration_days):
    """Use LLM to generate a structured campaign plan."""
    try:
        from apps.agents.llm import generate, get_model_for_task

        platform_list = ", ".join(platforms)
        system = (
            f"You are a marketing campaign strategist for {business_name or 'a business'}.\n"
            f"Brand voice: {brand_voice or 'professional and engaging'}.\n"
            f"Connected platforms: {platform_list}.\n"
            f"Campaign duration: {duration_days} days."
        )

        user_prompt = (
            f"Create a campaign plan for this goal:\n\n{prompt}\n\n"
            f"Return ONLY valid JSON with this structure:\n"
            f'{{\n'
            f'  "name": "Short campaign name (max 60 chars)",\n'
            f'  "description": "One-paragraph campaign description",\n'
            f'  "objective": "awareness|engagement|traffic|leads|sales|brand",\n'
            f'  "target_audience": "Who this campaign targets",\n'
            f'  "seeds": [\n'
            f'    {{\n'
            f'      "idea": "Detailed content idea with angle and key message",\n'
            f'      "platforms": ["platform1", "platform2"],\n'
            f'      "day": 1\n'
            f'    }}\n'
            f'  ]\n'
            f'}}\n\n'
            f"Generate 4-7 content seeds spread across {duration_days} days.\n"
            f"Each seed should have a unique angle — don't repeat the same message.\n"
            f"Mix content types: educational, social proof, behind-the-scenes, CTA-focused.\n"
            f"Assign each seed to 1-2 of the most appropriate platforms."
        )

        model = get_model_for_task("create.strategize", user=user)
        resp = generate(
            model=model, system=system, prompt=user_prompt,
            temperature=0.7, max_tokens=1500,
        )

        if resp and resp.text:
            text = resp.text.strip()
            # Strip markdown code fences if present
            if text.startswith("```"):
                text = text.split("\n", 1)[1] if "\n" in text else text[3:]
                if text.endswith("```"):
                    text = text[:-3]
            return json.loads(text.strip())
    except Exception as e:
        logger.error("Campaign plan generation failed: %s", e)

    return None
