# Generated by Django 5.1.15 on 2026-03-27 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_text', models.TextField()),
                ('content_type', models.CharField(choices=[('original', 'Original'), ('repurposed', 'Repurposed'), ('curated', 'Curated'), ('reply', 'Reply')], default='original', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing...'), ('published', 'Published'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by_agent', models.CharField(blank=True, max_length=100)),
                ('predicted_engagement_score', models.FloatField(blank=True, null=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why the agent chose this content/timing.')),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('platform_post_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='post_media/%Y/%m/')),
                ('file_type', models.CharField(max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
