# Generated by Django 5.1.15 on 2026-03-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentseed_post_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentseed',
            name='batch_strategy',
            field=models.TextField(blank=True, help_text='AI-generated content strategy for this batch of posts.'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_angle',
            field=models.CharField(blank=True, help_text='The strategic angle chosen for this platform.', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_framework',
            field=models.CharField(blank=True, help_text='Content framework used (e.g. Hook→Value→CTA).', max_length=100),
        ),
    ]
