# Generated by Django 5.1.15 on 2026-04-03 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_performance_indexes'),
        ('platforms', '0004_encrypt_oauth_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='variant_label',
            field=models.CharField(blank=True, help_text='Variant label: A, B, C…', max_length=10),
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variant_count', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('generating', 'Generating Variants'), ('draft', 'Variants Ready'), ('running', 'Running'), ('concluded', 'Concluded'), ('cancelled', 'Cancelled')], db_index=True, default='generating', max_length=20)),
                ('test_duration_hours', models.PositiveIntegerField(default=48, help_text='Hours after last variant published before declaring winner.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('conclusion_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='content.contentseed')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.post')),
            ],
            options={
                'verbose_name': 'A/B Test',
                'verbose_name_plural': 'A/B Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='content.abtest'),
        ),
    ]
