# Generated by Django 5.1.15 on 2026-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_ab_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_original_text',
            field=models.TextField(blank=True, help_text='Original AI-generated text before user edits. Set once during generation, never overwritten.'),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_distance_ratio',
            field=models.FloatField(blank=True, help_text='0.0 = no changes, 1.0 = completely rewritten. Measures how much user changed AI output.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_edited',
            field=models.BooleanField(default=False, help_text='Whether the user modified the AI-generated content.'),
        ),
    ]
