# Generated by Django 5.1.15 on 2026-04-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_media_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cta_text',
            field=models.CharField(blank=True, help_text="CTA copy, e.g. 'Book a free consultation →'", max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_type',
            field=models.CharField(choices=[('none', 'No CTA'), ('link', 'Link / URL'), ('phone', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('kova_link', 'Kova Link Page')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Destination URL or contact info for the CTA.', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='first_comment',
            field=models.TextField(blank=True, help_text='For LinkedIn: CTA link goes in first comment instead of body.'),
        ),
        migrations.AddField(
            model_name='post',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='From seed or user campaign.', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='utm_content',
            field=models.CharField(blank=True, help_text='Post ID for A/B tracking.', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='utm_medium',
            field=models.CharField(blank=True, default='social', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='utm_source',
            field=models.CharField(blank=True, help_text='Auto-populated from platform name.', max_length=50),
        ),
    ]
