# Generated by Django 5.1.15 on 2026-04-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_visual_strategy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentseed',
            name='generate_images',
            field=models.BooleanField(default=False, help_text='When True, generate AI images for ALL platforms (not just visual-first ones like Instagram).'),
        ),
    ]
