# Generated by Django 5.1.15 on 2026-04-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_post_user_rating'),
        ('products', '0003_product_additional_images_product_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentseed',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this seed promotes. Enables product-to-content pipeline tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_seeds', to='products.product'),
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this post promotes. Inherited from seed or set directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='products.product'),
        ),
    ]
