# Generated by Django 5.1.15 on 2026-04-18 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_goal_metric_campaign_goal_target'),
        ('content', '0016_contentseed_product_post_product'),
        ('emails', '0006_emailsubscriber_unsubscribe_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(help_text='Audio file (mp3, m4a, ogg, wav, webm) — max 5 minutes', upload_to='voice_briefs/%Y/%m/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration extracted from audio metadata', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing Audio'), ('extracting', 'Extracting Intent'), ('generating', 'Generating Campaign'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=15)),
                ('transcript', models.TextField(blank=True, help_text='Whisper-generated transcript of the voice memo')),
                ('language_detected', models.CharField(blank=True, help_text='Detected language code (en, sw, sheng, etc.)', max_length=10)),
                ('ai_extraction', models.JSONField(blank=True, default=dict, help_text='Structured extraction from transcript:\n{"products": ["Samsung A54"], "platforms": ["instagram", "facebook"],\n "urgency": "this_week", "audience": "students",\n "cta_type": "whatsapp", "tone": "excited",\n "key_message": "Back in stock at KES 45,000",\n "include_email": true, "budget_hint": null}')),
                ('seeds_created', models.PositiveIntegerField(default=0, help_text='Number of content seeds generated')),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Total wall-clock processing time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='The campaign auto-generated from this voice brief', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_briefs', to='campaigns.campaign')),
                ('email_campaign', models.ForeignKey(blank=True, help_text='Optional email campaign generated if user mentioned email/subscribers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_briefs', to='emails.emailcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='content_voi_user_id_a6e090_idx'), models.Index(fields=['user', '-created_at'], name='content_voi_user_id_97e9c1_idx')],
            },
        ),
    ]
