# Generated by Django 5.1.15 on 2026-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_voicebrief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_comment',
            field=models.TextField(blank=True, help_text='First comment to post immediately after publishing. Used for Facebook (links in body reduce organic reach 50-70%) and LinkedIn (link-in-comments drives more profile clicks). Auto-populated for Facebook when a product or website URL is available.'),
        ),
    ]
