# Generated by Django 5.1.15 on 2026-05-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_post_first_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentseed',
            name='target_intent',
            field=models.CharField(blank=True, choices=[('problem_awareness', 'Problem Awareness'), ('solution', 'Solution Education'), ('proof', 'Proof / Testimonial'), ('offer', 'Offer / CTA'), ('authority', 'Authority / Expertise')], help_text='Content intent the Strategist wants this seed to target.', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='content_intent',
            field=models.CharField(blank=True, choices=[('problem_awareness', 'Problem Awareness'), ('solution', 'Solution Education'), ('proof', 'Proof / Testimonial'), ('offer', 'Offer / CTA'), ('authority', 'Authority / Expertise')], help_text='What this post is designed to do: attract attention, educate, prove, offer, or build authority.', max_length=30),
        ),
    ]
