# Generated by Django 4.2.23 on 2026-06-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_products_ba_user_ty_idx_products_bu_user_id_be6075_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0033_contentseed_blueprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('objective', models.CharField(choices=[('sales', 'Sales'), ('leads', 'Leads'), ('awareness', 'Awareness'), ('bookings', 'Bookings')], default='sales', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Ready for review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, help_text='Campaign quality 0–100 from blueprint QA.', null=True)),
                ('proposal_meta', models.JSONField(blank=True, default=dict, help_text='Seed proposal angle, formats, rationale when picked from multi-proposal flow.')),
                ('commerce_url', models.URLField(blank=True, help_text='Campaign or product commerce page CTA.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='products.businessasset')),
                ('content_seed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaign', to='content.contentseed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='content_mar_user_id_3f6cd2_idx'), models.Index(fields=['user', '-created_at'], name='content_mar_user_id_aa92b2_idx')],
            },
        ),
    ]
