# Generated by Django 4.2.23 on 2026-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_legacy_campaign_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentseed',
            name='template_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Canonical Template Family key (e.g. offer, booking_cta). See template_families.py.', max_length=40),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='template_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Canonical Template Family key selected for this campaign.', max_length=40),
        ),
    ]
