# Generated by Django 4.2.23 on 2026-09-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_template_family_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentseed',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='post',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='voicebrief',
            name='email_campaign',
        ),
    ]
