# Generated by Django 5.1.15 on 2026-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaction',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentaction',
            name='model_used',
            field=models.CharField(blank=True, help_text='LLM model identifier used for this action', max_length=100),
        ),
        migrations.AddField(
            model_name='agentaction',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
