# Generated by Django 5.1.15 on 2026-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaction',
            name='outcome_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured outcome: {posts_created, avg_engagement, user_edits, prediction_accuracy, etc.}'),
        ),
        migrations.AddField(
            model_name='agentaction',
            name='outcome_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentaction',
            name='outcome_score',
            field=models.FloatField(blank=True, help_text='Measured outcome (0-100). E.g. engagement rate of generated posts, accuracy of prediction.', null=True),
        ),
    ]
