# Generated by Django 5.1.15 on 2026-04-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_llmconfig_default_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='image_default_model',
            field=models.CharField(default='black-forest-labs/FLUX.1-schnell', help_text='Default image model when no plan-specific model is configured.', max_length=120),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='image_default_provider',
            field=models.CharField(default='together', help_text='Primary image provider: together, huggingface, pollinations.', max_length=30),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='image_enabled',
            field=models.BooleanField(default=True, help_text='Global kill-switch for AI image generation.'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='image_fallback_chain',
            field=models.JSONField(blank=True, default=list, help_text='Ordered fallback providers: ["together", "huggingface", "pollinations"]'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='image_plan_models',
            field=models.JSONField(blank=True, default=dict, help_text='Per-plan image model routing. {"starter": {"model": "...", "provider": "together"}, ...}'),
        ),
        migrations.AlterField(
            model_name='agentaction',
            name='agent_type',
            field=models.CharField(choices=[('research', 'Research Agent'), ('create', 'Content Creator Agent'), ('adapt', 'Platform Adapter Agent'), ('engage', 'Engagement Agent'), ('analyst', 'Analytics Agent'), ('strategist', 'Chief Strategist & Growth Advisor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='agent_type',
            field=models.CharField(choices=[('research', 'Research Agent'), ('create', 'Content Creator Agent'), ('adapt', 'Platform Adapter Agent'), ('engage', 'Engagement Agent'), ('analyst', 'Analytics Agent'), ('strategist', 'Chief Strategist & Growth Advisor')], max_length=20),
        ),
    ]
