# Generated by Django 5.1.15 on 2026-05-02 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_image_config_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_date', models.DateField(db_index=True)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_usd_micros', models.PositiveBigIntegerField(default=0)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_buckets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['user', '-period_date'], name='agents_user_user_id_40c832_idx')],
                'unique_together': {('user', 'period_date')},
            },
        ),
    ]
