# Generated by Django 5.1.15 on 2026-05-16 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_goal_metric_campaign_goal_target'),
        ('content', '0018_alter_post_first_comment'),
        ('qr_attribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(help_text='What customers see at the top of the booking page.', max_length=200)),
                ('industry_template', models.CharField(choices=[('salon', 'Salon / Beauty'), ('real_estate', 'Real estate viewing'), ('fitness', 'Fitness / training'), ('consultant', 'Consultant / coach'), ('clinic', 'Clinic / health'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('services', models.JSONField(blank=True, default=list, help_text='List of bookable services. Shape: [{name, duration_minutes, price_kes}, ...]')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Per-weekday open windows. Keys mon/tue/.../sun, value list of {start, end} in HH:MM.')),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=40)),
                ('advance_notice_minutes', models.PositiveIntegerField(default=120, help_text="Customers can't book within this many minutes of now.")),
                ('max_advance_days', models.PositiveIntegerField(default=30, help_text="Customers can't book more than this many days out.")),
                ('owner_whatsapp', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('service_name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], db_index=True, default='confirmed', max_length=20)),
                ('source_channel', models.CharField(blank=True, help_text='engage_agent, qr, direct, walk_in, manual', max_length=40)),
                ('customer_confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner_confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='campaigns.campaign')),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='content.post')),
                ('source_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='qr_attribution.qrcode')),
                ('booking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.bookinglink')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookinglink',
            index=models.Index(fields=['user', '-created_at'], name='bookings_bo_user_id_6aa339_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinglink',
            index=models.Index(fields=['user', 'is_active'], name='bookings_bo_user_id_049ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_link', 'scheduled_at'], name='bookings_bo_booking_376b26_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_link', 'status', '-scheduled_at'], name='bookings_bo_booking_bda6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_at'], name='bookings_bo_status_8276e1_idx'),
        ),
    ]
