# Generated by Django 5.1.15 on 2026-05-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_link', 'scheduled_at')},
        ),
    ]
