# Generated by Django 4.2.23 on 2026-06-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_legacy_campaign_app'),
        ('bookings', '0002_add_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='content.marketingcampaign'),
        ),
    ]
