# Generated by Django 5.1.15 on 2026-03-27 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('summary', models.TextField(help_text="Plain-language summary of the day's plan.")),
                ('trending_topics', models.JSONField(blank=True, default=list)),
                ('suggested_posts', models.JSONField(blank=True, default=list, help_text='List of post suggestions with reasoning.')),
                ('performance_summary', models.JSONField(blank=True, default=dict, help_text="Yesterday's performance data.")),
                ('agent_activity', models.JSONField(blank=True, default=list, help_text='What agents did/plan to do.')),
                ('posts_pending', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
