# Generated by Django 5.1.15 on 2026-04-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailybrief',
            index=models.Index(fields=['user', '-date'], name='briefs_dail_user_id_b1088c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybrief',
            index=models.Index(fields=['user', 'is_read', '-date'], name='briefs_dail_user_id_a391d9_idx'),
        ),
    ]
