# Generated by Django 5.1.15 on 2026-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0004_briefwhatsapplog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='briefwhatsapplog',
            new_name='briefs_brie_created_c9843c_idx',
            old_name='briefs_brie_created_6a1b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='briefwhatsapplog',
            new_name='briefs_brie_user_id_34ba64_idx',
            old_name='briefs_brie_user_id_8c4f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='briefwhatsapplog',
            new_name='briefs_brie_command_687283_idx',
            old_name='briefs_brie_command_91e3bc_idx',
        ),
        migrations.AddField(
            model_name='dailybrief',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
