# Generated by Django 5.1.15 on 2026-04-05 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('from_email', models.EmailField(default='', max_length=254)),
                ('email_type', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('welcome', 'Welcome'), ('payment_confirmation', 'Payment Confirmation'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('payment_failed', 'Payment Failed'), ('payment_reminder', 'Payment Reminder'), ('plan_changed', 'Plan Changed'), ('subscription_canceled', 'Subscription Canceled'), ('trial_ending', 'Trial Ending'), ('team_invitation', 'Team Invitation'), ('weekly_report', 'Weekly Report'), ('daily_brief', 'Daily Brief'), ('feature_announcement', 'Feature Announcement'), ('promotional', 'Promotional'), ('usage_warning', 'Usage Warning'), ('system', 'System')], db_index=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('spam', 'Marked as Spam')], db_index=True, default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, help_text='Null for emails sent to non-users (e.g. team invitations).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type', '-created_at'], name='emails_emai_email_t_6b0a6e_idx'), models.Index(fields=['status', '-created_at'], name='emails_emai_status_f6924b_idx'), models.Index(fields=['user', '-created_at'], name='emails_emai_user_id_d6ae13_idx')],
            },
        ),
    ]
