# Generated by Django 5.1.15 on 2026-04-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('welcome', 'Welcome'), ('payment_confirmation', 'Payment Confirmation'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('payment_failed', 'Payment Failed'), ('payment_reminder', 'Payment Reminder'), ('plan_changed', 'Plan Changed'), ('subscription_canceled', 'Subscription Canceled'), ('trial_ending', 'Trial Ending'), ('team_invitation', 'Team Invitation'), ('weekly_report', 'Weekly Report'), ('daily_brief', 'Daily Brief'), ('feature_announcement', 'Feature Announcement'), ('promotional', 'Promotional'), ('partner_app_received', 'Partner Application Received'), ('partner_app_approved', 'Partner Application Approved'), ('partner_app_rejected', 'Partner Application Rejected'), ('partner_new_referral', 'Partner New Referral'), ('partner_milestone', 'Partner Milestone Achieved'), ('usage_warning', 'Usage Warning'), ('system', 'System')], db_index=True, max_length=30),
        ),
    ]
