# Generated by Django 5.1.15 on 2026-04-08 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_post_cta_text_post_cta_type_post_cta_url_and_more'),
        ('emails', '0003_alter_emaillog_email_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('kova_form', 'Kova Form'), ('manual', 'Manual Entry'), ('import', 'CSV Import'), ('social_bio', 'Social Bio Link'), ('api', 'API'), ('lead_sync', 'Lead Sync')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='active', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('engagement_score', models.FloatField(default=50.0, help_text='0-100 engagement health score.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('filter_rules', models.JSONField(blank=True, default=dict, help_text='Smart list filter rules: tags, source, engagement_score range, etc.')),
                ('is_smart', models.BooleanField(default=False, help_text='Smart lists auto-populate from filter rules instead of manual assignment.')),
                ('subscriber_count', models.PositiveIntegerField(default=0, help_text='Cached count for display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal campaign name.', max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(blank=True, help_text='The preview snippet in inbox.', max_length=255)),
                ('html_content', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True, help_text='Plain text fallback.')),
                ('from_name', models.CharField(blank=True, help_text='Sender display name.', max_length=200)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_opened', models.PositiveIntegerField(default=0)),
                ('total_clicked', models.PositiveIntegerField(default=0)),
                ('total_bounced', models.PositiveIntegerField(default=0)),
                ('total_unsubscribed', models.PositiveIntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('variant_label', models.CharField(blank=True, help_text='A, B, C…', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('variant_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='emails.emailcampaign')),
                ('target_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='emails.emaillist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('form_submission', 'Form Submission'), ('tag_added', 'Tag Added'), ('subscriber_added', 'Subscriber Added'), ('lead_status_change', 'Lead Status Change'), ('manual', 'Manual Enrollment')], max_length=30)),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Trigger params: form_id, tag_name, list_id, etc.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSequenceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('delay_days', models.PositiveSmallIntegerField(default=0, help_text='Days after previous step.')),
                ('delay_hours', models.PositiveSmallIntegerField(default=0, help_text='Hours after previous step.')),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='emails.emailsequence')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
