# Generated by Django 5.1.15 on 2026-04-08 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailsubscriber_sequenceenrollment_emaillist_and_more'),
        ('leads', '0001_initial'),
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='source_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='links.kovaform'),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaillist',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='lists', to='emails.emailsubscriber'),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='emails.emailsequence'),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='emails.emailsubscriber'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['user', 'status', '-created_at'], name='emails_emai_user_id_7dabd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailsequencestep',
            unique_together={('sequence', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='emailsubscriber',
            index=models.Index(fields=['user', 'status', '-subscribed_at'], name='emails_emai_user_id_c9a203_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsubscriber',
            index=models.Index(fields=['email'], name='emails_emai_email_c33fe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailsubscriber',
            unique_together={('user', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='sequenceenrollment',
            unique_together={('sequence', 'subscriber')},
        ),
    ]
