# Generated by Django 5.1.15 on 2026-04-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailsubscriber_lead_emailsubscriber_source_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True),
        ),
    ]
