# Generated by Django 5.1.15 on 2026-03-31 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Competitor brand/business name', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text="What they do, why you're tracking them")),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('facebook_handle', models.CharField(blank=True, max_length=255)),
                ('linkedin_handle', models.CharField(blank=True, max_length=255)),
                ('tiktok_handle', models.CharField(blank=True, max_length=100)),
                ('youtube_handle', models.CharField(blank=True, max_length=100)),
                ('threads_handle', models.CharField(blank=True, max_length=100)),
                ('strengths', models.JSONField(blank=True, default=list, help_text='AI-identified content strengths')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='AI-identified content gaps/weaknesses')),
                ('content_patterns', models.JSONField(blank=True, default=dict, help_text='Detected content patterns: formats, themes, frequency, tone')),
                ('threat_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='How much of a competitive threat', max_length=20)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('full', 'Full Analysis'), ('quick', 'Quick Check'), ('comparison', 'Head-to-Head Comparison')], default='full', max_length=20)),
                ('summary', models.TextField(help_text='Executive summary of what this competitor is doing')),
                ('content_strategy', models.JSONField(default=dict, help_text='Detected strategy: themes, formats, frequency, tone, best-performing')),
                ('strengths', models.JSONField(default=list, help_text='What they do well')),
                ('weaknesses', models.JSONField(default=list, help_text='Where they fall short')),
                ('opportunities', models.JSONField(default=list, help_text='Gaps you can exploit — things they miss that you could do')),
                ('threats', models.JSONField(default=list, help_text='Things they do that threaten your positioning')),
                ('comparison_to_user', models.JSONField(default=dict, help_text="Head-to-head: where you're winning vs losing")),
                ('actionable_insights', models.JSONField(default=list, help_text="Specific content ideas inspired by this competitor's gaps")),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics.competitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Competitor analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('content_gap', 'Content Gap'), ('trend_ahead', "They're Ahead on a Trend"), ('weakness', 'Exploitable Weakness'), ('strategy_shift', 'Strategy Shift Detected'), ('viral_content', 'Viral Content Alert'), ('opportunity', 'Opportunity')], max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High — Act Now'), ('medium', 'Medium — This Week'), ('low', 'Low — Good to Know')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(blank=True, help_text='What the user should do about this')),
                ('suggested_content_idea', models.TextField(blank=True, help_text='A specific content seed idea inspired by this insight')),
                ('is_acted_on', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.competitoranalysis')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.competitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
