# Generated by Django 5.1.15 on 2026-04-11 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_conversion_product_conversionjourney_and_more'),
        ('platforms', '0006_socialaccount_platforms_s_user_id_479427_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0, help_text='Total posts on the platform')),
                ('followers_delta', models.IntegerField(default=0, help_text='Change in followers since previous snapshot')),
                ('posts_delta', models.IntegerField(default=0, help_text='Posts published since previous snapshot')),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_snapshots', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', '-snapshot_date'], name='analytics_g_user_id_187df0_idx'), models.Index(fields=['social_account', '-snapshot_date'], name='analytics_g_social__8041e4_idx')],
                'unique_together': {('social_account', 'snapshot_date')},
            },
        ),
    ]
