# Generated by Django 5.1.15 on 2026-04-17 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_websiteevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('brief', 'Daily Brief'), ('content', 'Content Studio'), ('engage', 'Inbox (Engage)'), ('whatsapp', 'WhatsApp'), ('agents', 'Agents'), ('analytics', 'Analytics / Insights'), ('attribution', 'Attribution'), ('intelligence', 'Content Intelligence'), ('competitors', 'Competitors'), ('leads', 'Lead Inbox'), ('nurture', 'Nurture Sequences'), ('links', 'Kova Links'), ('products', 'Products'), ('campaigns', 'Campaigns'), ('memes', 'Meme Studio'), ('media_queue', 'Media Queue'), ('billing', 'Billing'), ('teams', 'Teams'), ('emails', 'Email Marketing'), ('notifications', 'Notifications'), ('help', 'Help Center'), ('settings', 'Account Settings'), ('other', 'Other')], db_index=True, max_length=30)),
                ('path', models.CharField(max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'section', '-viewed_at'], name='analytics_p_user_id_c48d7c_idx'), models.Index(fields=['section', '-viewed_at'], name='analytics_p_section_4b05eb_idx'), models.Index(fields=['-viewed_at'], name='analytics_p_viewed__863699_idx')],
            },
        ),
    ]
