# Generated by Django 5.1.15 on 2026-04-03 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(choices=[('center', 'Help Center'), ('article', 'Article')], max_length=20)),
                ('article_slug', models.CharField(blank=True, default='', max_length=120)),
                ('article_title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['article_slug', 'viewed_at'], name='help_helppa_article_160961_idx'), models.Index(fields=['user', 'viewed_at'], name='help_helppa_user_id_8c6430_idx')],
            },
        ),
    ]
