# Generated by Django 5.1.15 on 2026-04-22 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, default='', help_text='Short description shown on cards and in search results.', max_length=300)),
                ('body_md', models.TextField(blank=True, default='', help_text='Markdown source. Rendered to body_html on save.')),
                ('body_html', models.TextField(blank=True, default='', help_text='Cached HTML rendered from body_md.')),
                ('category', models.CharField(choices=[('getting-started', 'Getting Started'), ('content', 'Content & Publishing'), ('agents', 'AI Agents'), ('analytics', 'Analytics & Insights'), ('account', 'Account & Billing'), ('tips', 'Tips & Best Practices'), ('product-updates', 'Product Updates')], db_index=True, default='getting-started', max_length=30)),
                ('audience', models.CharField(choices=[('user', 'In-product users'), ('prospect', 'Public / prospects'), ('both', 'Both')], db_index=True, default='user', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Ready for Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order within a category. Lower = earlier.')),
                ('hero_image', models.CharField(blank=True, default='', help_text="URL to the article's hero image (R2 or external).", max_length=500)),
                ('meta_title', models.CharField(blank=True, default='', help_text='SEO <title>. Falls back to title when blank.', max_length=70)),
                ('meta_description', models.CharField(blank=True, default='', help_text='SEO meta description. Falls back to excerpt when blank.', max_length=160)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1)),
                ('author_agent', models.CharField(blank=True, default='', help_text="Agent that drafted this article (e.g. 'educator'). Blank if human-authored.", max_length=30)),
                ('legacy_template', models.CharField(blank=True, default='', help_text='Legacy template path for migrated articles. Blank for markdown-rendered articles.', max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Founder/staff user who approved publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
                'indexes': [models.Index(fields=['status', 'audience', '-published_at'], name='help_articl_status_7abc8e_idx'), models.Index(fields=['category', 'order'], name='help_articl_categor_5c9f28_idx')],
            },
        ),
    ]
