# Generated by Django 5.1.15 on 2026-04-22 22:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_seed_articles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField(blank=True, default='', help_text='Markdown description, 1-3 sentences. Shown in the newsletter.')),
                ('category', models.CharField(choices=[('feature', 'New Feature'), ('improvement', 'Improvement'), ('fix', 'Fix'), ('announcement', 'Announcement')], db_index=True, default='feature', max_length=15)),
                ('shipped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True, help_text='Include in public newsletter. Uncheck for internal-only notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_article', models.ForeignKey(blank=True, help_text='Optional deep-dive article for this change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog_mentions', to='help.article')),
            ],
            options={
                'verbose_name_plural': 'Changelog entries',
                'ordering': ['-shipped_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_end', models.DateField(help_text='Sunday (inclusive) of the week this digest covers.', unique=True)),
                ('intro_html', models.TextField(blank=True, default='')),
                ('changelog_html', models.TextField(blank=True, default='')),
                ('articles_html', models.TextField(blank=True, default='')),
                ('stats_html', models.TextField(blank=True, default='')),
                ('raw_content', models.JSONField(blank=True, default=dict, help_text='Structured output from the Educator agent (before HTML render).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('skipped', 'Skipped')], db_index=True, default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digests_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_end'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('rationale', models.TextField(blank=True, default='', help_text='Why this topic matters — shown to the agent in its prompt.')),
                ('suggested_category', models.CharField(choices=[('getting-started', 'Getting Started'), ('content', 'Content & Publishing'), ('agents', 'AI Agents'), ('analytics', 'Analytics & Insights'), ('account', 'Account & Billing'), ('tips', 'Tips & Best Practices'), ('product-updates', 'Product Updates')], default='tips', max_length=30)),
                ('audience', models.CharField(choices=[('user', 'In-product users'), ('prospect', 'Public / prospects'), ('both', 'Both')], default='user', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Higher number = drafted sooner. 0-100.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('drafted', 'Drafted'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('research', 'Research agent'), ('gap', 'Content gap')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drafted_at', models.DateTimeField(blank=True, null=True)),
                ('drafted_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic', to='help.article')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', '-priority'], name='help_articl_status_dd02f1_idx')],
            },
        ),
    ]
