# Generated by Django 5.1.15 on 2026-04-22 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_educator_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], db_index=True, default='active', max_length=15)),
                ('source', models.CharField(choices=[('blog', 'Blog subscribe form'), ('landing', 'Landing page'), ('article', 'Article footer'), ('manual', 'Manual')], default='blog', max_length=20)),
                ('source_slug', models.CharField(blank=True, default='', help_text='If signed up from a specific article, the article slug.', max_length=120)),
                ('unsubscribe_token', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['status', '-subscribed_at'], name='help_newsle_status_d1aa82_idx')],
            },
        ),
    ]
