# Generated by Django 5.1.15 on 2026-05-11 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0007_alter_socialaccount_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness_score', models.PositiveSmallIntegerField(default=0, help_text='0-100. Weighted score of how complete the profile is.')),
                ('fields_present', models.JSONField(default=dict, help_text='{field_name: current_value} for fields the platform exposes')),
                ('fields_missing', models.JSONField(default=list, help_text='List of field names absent or empty on the profile.')),
                ('fields_thin', models.JSONField(default=list, help_text='Fields present but too short / placeholder-like.')),
                ('raw_profile', models.JSONField(blank=True, default=dict, help_text='Raw API response for debugging. Truncated to avoid huge rows.')),
                ('error', models.TextField(blank=True, help_text='If the audit itself failed (API error etc), the reason.')),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_audits', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audited_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUpdateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Platform-agnostic field key: bio, description, website, etc.', max_length=80)),
                ('current_value', models.TextField(blank=True, help_text="What's there now (empty if missing).")),
                ('suggested_value', models.TextField(help_text='What Kova proposes to write.')),
                ('reasoning', models.TextField(blank=True, help_text='One-line explanation surfaced in the UI so users know why the AI suggested this.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved — queued to apply'), ('applied', 'Applied successfully'), ('dismissed', 'Dismissed by user'), ('failed', 'Apply failed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_value', models.TextField(blank=True, help_text='The value the platform reports AFTER our PATCH. May differ slightly from suggested_value if the platform trims / normalizes (e.g., strips emoji, truncates).')),
                ('api_response', models.JSONField(blank=True, default=dict, help_text='Last API response — kept for debugging.')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='profile_audit.profileaudit')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_suggestions', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profileaudit',
            index=models.Index(fields=['user', '-audited_at'], name='profile_aud_user_id_ce353c_idx'),
        ),
        migrations.AddIndex(
            model_name='profileaudit',
            index=models.Index(fields=['social_account', '-audited_at'], name='profile_aud_social__cadacf_idx'),
        ),
        migrations.AddIndex(
            model_name='profileupdatesuggestion',
            index=models.Index(fields=['user', 'status'], name='profile_aud_user_id_6665f9_idx'),
        ),
        migrations.AddIndex(
            model_name='profileupdatesuggestion',
            index=models.Index(fields=['social_account', 'status'], name='profile_aud_social__e97edf_idx'),
        ),
        migrations.AddIndex(
            model_name='profileupdatesuggestion',
            index=models.Index(fields=['status', '-created_at'], name='profile_aud_status_d5e0f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileupdatesuggestion',
            constraint=models.UniqueConstraint(fields=('audit', 'field_name'), name='profile_suggestion_unique_per_audit_field'),
        ),
    ]
