# Generated by Django 5.1.15 on 2026-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_competitor_competitoranalysis_competitorinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetric',
            name='actual_score',
            field=models.FloatField(blank=True, help_text='Normalized actual engagement score (0-100) calculated from real metrics.', null=True),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='predicted_score',
            field=models.FloatField(blank=True, help_text='Snapshot of Post.predicted_engagement_score at publish time.', null=True),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='prediction_error',
            field=models.FloatField(blank=True, help_text='actual_score - predicted_score. Positive = underestimated, negative = overestimated.', null=True),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='prediction_validated_at',
            field=models.DateTimeField(blank=True, help_text='When the prediction was compared against actuals.', null=True),
        ),
    ]
