# Generated by Django 5.1.15 on 2026-04-04 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_postmetric_actual_score_postmetric_predicted_score_and_more'),
        ('content', '0008_contentseed_brand_post_brand'),
        ('platforms', '0004_encrypt_oauth_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(choices=[('click', 'Link Click'), ('lead', 'Lead / Sign-up'), ('sale', 'Sale'), ('custom', 'Custom Event')], default='click', max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue attributed to this conversion (0 if non-revenue event).', max_digits=10)),
                ('event_name', models.CharField(blank=True, help_text='Custom event label', max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, help_text='Usually the post ID', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='content.post')),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='platforms.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
