# Generated by Django 5.1.15 on 2026-04-06 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_conversion'),
        ('content', '0011_add_media_prompt'),
        ('platforms', '0006_socialaccount_platforms_s_user_id_479427_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitoranalysis',
            name='competitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analytics.competitor'),
        ),
        migrations.AlterField(
            model_name='competitoranalysis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='competitorinsight',
            index=models.Index(fields=['user', 'is_acted_on', '-created_at'], name='analytics_c_user_id_b31b08_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorinsight',
            index=models.Index(fields=['user', 'priority', '-created_at'], name='analytics_c_user_id_45e0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user', '-created_at'], name='analytics_c_user_id_fb5290_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['utm_campaign', '-created_at'], name='analytics_c_utm_cam_b19e09_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user', 'conversion_type', '-created_at'], name='analytics_c_user_id_6d60c9_idx'),
        ),
    ]
