# Generated by Django 5.1.15 on 2026-04-10 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_competitor_user_and_more'),
        ('content', '0012_post_cta_text_post_cta_type_post_cta_url_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product associated with this conversion (from Sprint 6H catalog).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='products.product'),
        ),
        migrations.CreateModel(
            name='ConversionJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, help_text='Anonymous visitor ID (cookie) or email for identified users.', max_length=255)),
                ('is_converted', models.BooleanField(default=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('touchpoint_count', models.PositiveIntegerField(default=0)),
                ('first_touch_at', models.DateTimeField(blank=True, null=True)),
                ('last_touch_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='analytics.conversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionTouchpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('touch_type', models.CharField(choices=[('post_click', 'Clicked Post Link'), ('page_view', 'Kova Page View'), ('link_click', 'Kova Link Click'), ('form_submit', 'Form Submission'), ('ad_click', 'Ad Click'), ('direct', 'Direct Visit')], max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('landing_page', models.URLField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=10)),
                ('touched_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='analytics.conversionjourney')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='content.post')),
            ],
            options={
                'ordering': ['touched_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_domain', models.CharField(help_text='myshop.myshopify.com', max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret for verifying Shopify webhook signatures.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('orders_tracked', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversionjourney',
            index=models.Index(fields=['user', 'visitor_id'], name='analytics_c_user_id_0cab2d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjourney',
            index=models.Index(fields=['user', 'is_converted', '-created_at'], name='analytics_c_user_id_1ee2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversiontouchpoint',
            index=models.Index(fields=['journey', 'touched_at'], name='analytics_c_journey_920df0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifystore',
            unique_together={('user', 'shop_domain')},
        ),
    ]
