# Generated by Django 5.1.15 on 2026-04-14 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_growth_snapshot'),
        ('content', '0015_post_user_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('form_submit', 'Form Submission'), ('button_click', 'Button Click'), ('purchase', 'Purchase'), ('add_to_cart', 'Add to Cart'), ('sign_up', 'Sign Up'), ('custom', 'Custom Event')], max_length=20)),
                ('event_name', models.CharField(blank=True, help_text='Custom event label', max_length=100)),
                ('page_url', models.URLField(max_length=2048)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('visitor_id', models.CharField(db_index=True, help_text='Anonymous cookie-based visitor ID set by the pixel.', max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_events', to='analytics.conversionjourney')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_events', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_w_user_id_481f23_idx'), models.Index(fields=['user', 'event_type', '-created_at'], name='analytics_w_user_id_e4c1c4_idx'), models.Index(fields=['visitor_id', '-created_at'], name='analytics_w_visitor_358a2b_idx'), models.Index(fields=['utm_source', 'utm_campaign'], name='analytics_w_utm_sou_2601f9_idx')],
            },
        ),
    ]
