# Generated by Django 5.1.15 on 2026-04-18 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_pageview'),
        ('content', '0016_contentseed_product_post_product'),
        ('emails', '0006_emailsubscriber_unsubscribe_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text="Screenshot of competitor's post, ad, story, or page", upload_to='competitor_screenshots/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'AI Analyzing Screenshot'), ('generating', 'Generating Counter-Posts'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=15)),
                ('user_notes', models.TextField(blank=True, help_text="Optional context from user: 'This is Jumia's Black Friday ad'")),
                ('competitor_name', models.CharField(blank=True, help_text='Competitor brand name extracted from screenshot', max_length=200)),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='AI analysis of the screenshot:\n{"platform": "instagram", "content_type": "ad",\n "messaging": "50% off sale — urgency + scarcity",\n "visual_style": "bright orange, product-focused, minimal text",\n "cta": "Shop Now", "estimated_engagement": "high",\n "strategy": "discount-led acquisition",\n "strengths": ["clear pricing", "strong visual"],\n "weaknesses": ["no social proof", "generic copy"],\n "hashtags": ["#BlackFriday", "#Deals"]}')),
                ('counter_strategy', models.TextField(blank=True, help_text="AI's explanation of the recommended counter-strategy")),
                ('posts_generated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('competitor', models.ForeignKey(blank=True, help_text='Auto-linked if competitor name matches an existing tracked competitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='analytics.competitor')),
                ('counter_seed', models.ForeignKey(blank=True, help_text='ContentSeed generated with counter-posts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_screenshots', to='content.contentseed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_screenshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='analytics_c_user_id_8438b6_idx'), models.Index(fields=['user', '-created_at'], name='analytics_c_user_id_df5cf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance_multiplier', models.DecimalField(decimal_places=2, help_text='How many times above average (e.g. 2.5 = 2.5x average engagement)', max_digits=5)),
                ('trigger_metric', models.CharField(help_text='Which metric triggered this: engagement_rate, impressions, clicks, shares, etc.', max_length=30)),
                ('status', models.CharField(choices=[('detected', 'Top Performer Detected'), ('generating', 'Generating Email Draft'), ('ready', 'Ready for Review'), ('sent', 'Email Sent'), ('dismissed', 'Dismissed')], db_index=True, default='detected', max_length=15)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body_html', models.TextField(blank=True, help_text="AI-generated email expanding on the post's topic")),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI thinks this post would make good email content')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_recycles', to='emails.emailcampaign')),
                ('post_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycles', to='analytics.postmetric')),
                ('source_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycles', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_recycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='analytics_p_user_id_619161_idx'), models.Index(fields=['user', '-detected_at'], name='analytics_p_user_id_9fcff6_idx')],
            },
        ),
    ]
