# Generated by Django 5.1.15 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_shopifystore_product_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='section',
            field=models.CharField(choices=[('brief', 'Today'), ('command', 'Workspace'), ('content', 'Content Studio'), ('engage', 'Inbox (Engage)'), ('whatsapp', 'WhatsApp'), ('agents', 'Agents'), ('analytics', 'Analytics / Insights'), ('attribution', 'Attribution'), ('intelligence', 'Content Intelligence'), ('competitors', 'Competitors'), ('leads', 'Lead Inbox'), ('nurture', 'Nurture Sequences'), ('links', 'Kova Links'), ('products', 'Snap2sell'), ('campaigns', 'Campaigns'), ('memes', 'Meme Studio'), ('media_queue', 'Media Queue'), ('billing', 'Billing'), ('teams', 'Teams'), ('emails', 'Email Marketing'), ('notifications', 'Notifications'), ('help', 'Help Center'), ('settings', 'Account Settings'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
