# Generated by Django 4.2.23 on 2026-09-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_conversion_marketing_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversion',
            new_name='analytics_c_user_id_3eb114_idx',
            old_name='analytics_c_user_id_camp_idx',
        ),
        migrations.RemoveField(
            model_name='performancerecycle',
            name='email_campaign',
        ),
    ]
