# Generated by Django 5.1.15 on 2026-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='user_edited_reply',
            field=models.BooleanField(default=False, help_text='Whether the user modified the AI-suggested reply before sending.'),
        ),
    ]
