# Generated by Django 5.1.15 on 2026-04-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_postversion_abtest_platform_post_deleted_at_and_more'),
        ('engage', '0004_interaction_user_edited_reply'),
        ('platforms', '0006_socialaccount_platforms_s_user_id_479427_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='platform',
            field=models.CharField(blank=True, db_index=True, help_text='Denormalized platform name — preserved when social_account is disconnected.', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='platforms.socialaccount'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user', 'status', '-created_at'], name='engage_inte_user_id_f720ac_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['social_account', '-created_at'], name='engage_inte_social__259d07_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user', 'sentiment', '-created_at'], name='engage_inte_user_id_89c952_idx'),
        ),
    ]
