# Generated by Django 5.1.15 on 2026-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0005_interaction_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the first reply (AI or human) was sent.', null=True),
        ),
    ]
