# Generated by Django 5.1.15 on 2026-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0006_interaction_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='Engage Agent LLM confidence in the suggested reply (0.0-1.0).', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='ai_intent',
            field=models.CharField(blank=True, db_index=True, help_text='Classified intent: hours, booking, pricing, complaint, praise, spam, other. Used by safety rails to gate auto-send.', max_length=30),
        ),
        migrations.AddField(
            model_name='interaction',
            name='safety_flags',
            field=models.JSONField(blank=True, default=list, help_text='Reasons the reply must NOT auto-send regardless of confidence. Populated by engage_routing.safety_check (complaint, long_reply, refund_keyword, cold_first_contact, pricing_without_cta, etc.).'),
        ),
    ]
