# Generated by Django 5.1.15 on 2026-05-15 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0007_engage_autonomy_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_text', models.TextField(help_text='The exact text that was auto-sent to the platform.')),
                ('confidence', models.FloatField(help_text='LLM confidence at send time (0.0-1.0).')),
                ('autonomy_level', models.CharField(help_text="Snapshot of the user's engage_autonomy_level when this reply was sent. Lets us audit later if a plan downgrade should have blocked it.", max_length=20)),
                ('safety_flags_snapshot', models.JSONField(blank=True, default=list, help_text='The safety_flags list at send time (empty when clean).')),
                ('platform_reply_id', models.CharField(blank=True, db_index=True, help_text="The platform's comment/reply ID returned from post_comment. Used by undo to call provider.delete_comment.", max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('can_undo_until', models.DateTimeField(help_text='5 minutes after sent_at by default. After this, only the correction flow remains.')),
                ('undone_at', models.DateTimeField(blank=True, help_text='When the user successfully undid the auto-send.', null=True)),
                ('undo_error', models.TextField(blank=True, help_text='If the platform delete API failed during undo, the error text.')),
                ('correction_text', models.TextField(blank=True, help_text='What the user would have said instead.')),
                ('correction_reason', models.CharField(blank=True, choices=[('tone', 'Wrong tone'), ('facts', 'Wrong facts'), ('length', 'Wrong length'), ('timing', 'Wrong timing / should have escalated'), ('other', 'Other')], help_text='High-level reason the auto-send was wrong.', max_length=20)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engage_reply', to='engage.interaction')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['interaction'], name='engage_enga_interac_f0f163_idx'), models.Index(fields=['sent_at'], name='engage_enga_sent_at_e6a41e_idx')],
            },
        ),
    ]
