# Generated by Django 5.1.15 on 2026-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0002_dailybrief_briefs_dail_user_id_b1088c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybrief',
            name='kova_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Social health score 0-100'),
        ),
        migrations.AddField(
            model_name='dailybrief',
            name='kova_score_delta',
            field=models.SmallIntegerField(default=0, help_text='Change from previous brief'),
        ),
        migrations.AddField(
            model_name='dailybrief',
            name='overnight_work',
            field=models.JSONField(blank=True, default=dict, help_text='What agents did overnight: {posts_created, trends_found, competitors_analyzed, engagements_handled}'),
        ),
    ]
