# Generated by Django 5.1.15 on 2026-04-14 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notificatio_user_id_f2ad08_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_published', models.BooleanField(default=True, help_text='Notify when a post is published')),
                ('publish_failed', models.BooleanField(default=True, help_text='Notify when publishing fails')),
                ('posts_generated', models.BooleanField(default=True, help_text='Notify when new posts are generated')),
                ('agent_action', models.BooleanField(default=True, help_text='Notify when agents take actions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
